PE-458: ArFS Tag Builder
ardriveapp/ardrive-core-js pull request #106
Opened 2021-12-14 16:59 UTC by fedellen

This PR adds the `ArFSTagBuilder` class which will now be responsible for handling base ArFS tx tags, tip tx tags, and bundle tx tags. It comes wrapped in its own unit tests and is used within the ArFSDAO and ArDrive classes.

The tag builder is meant to solve a circular dependency problem with passing base tags around. Estimating dataItems does require knowing the exact character length of every tag. This means that we need all of the tags fully constructed within the ArDrive layer to accurately estimate and assert an action. We use this calculation passed down as a `rewardSetting` to avoid a network request price check during transaction creation.

The refactor here causes `appVersion` and `appName` to be deprecated fields within the ArDrive and ArFSDAO class constructors. We will deprecate for now to maintain backwards compatibility, and during the next major version bump we can re-evaluate and re-structure our constructor params. The updated ArDrive Factory remains the ideal way to construct all classes with simple params

2021-12-14 17:00 UTC, fedellen commented on src/ardrive.test.ts
> +		// const bundledCostEstimator = new ArFSCostEstimator({ bundle: false, arFSTagBuilder, priceEstimator });
Excise

2021-12-14 17:02 UTC, fedellen commented on src/ardrive.ts
> -		private readonly bundle: boolean = true,
Good to note here for the reviewer that the `bundle` setting now exclusively lives in the `ArFSCostEstimator`. We infer whether to bundle or not bases on how we estimated the cost of the tx

2021-12-14 17:05 UTC, fedellen commented on src/arfs/arfs_tag_builder.test.ts
> +		it('returns provided tags combined with the base arfs tags', () => {
Update test desc

2021-12-14 17:05 UTC, fedellen commented on src/arfs/arfs_tag_builder.test.ts
> +		it('can exclude any specified tags names ', () => {
Whitespace at end

2021-12-14 22:42 UTC, arielmelendez commented on src/arfs/arfs_tag_builder.test.ts
> +			expect(arFSTagBuilder.withBaseArFSTags([], ['App-Version', 'ArFS'])).to.deep.equal([
Seeing this API used this way, it makes me think that object params might be beneficial so that the excludes aren't visually confused with anything else. Another option could be to provide them at construction time of the builder.

2021-12-14 22:42 UTC, arielmelendez commented on src/arfs/arfs_tag_builder.test.ts
> +			expect(arFSTagBuilder.withBaseArFSTags([], ['App-Version', 'ArFS'])).to.deep.equal([
To be clear: I understand the type checking would prevent any issues (even in the case of empty arrays), but I think readability could be enhanced.

2021-12-14 22:46 UTC, arielmelendez commented on src/arfs/arfs_tag_builder.test.ts
> +describe('ArFSTagBuilder class', () => {
Most "Builder" classes' APIs allow you to pump data in and then call a `build()` function which would potentially through an error if any validation checks fail. This class is more of a `Helper`. Consider a name change.

2021-12-14 22:47 UTC, arielmelendez commented on src/arfs/arfs_tag_builder.ts
> +		private readonly appName: string,
Consider object params as all three of these are easily interchangeable.

2021-12-14 22:56 UTC, arielmelendez commented on src/arfs/arfs_tag_builder.ts
> +export class ArFSTagBuilder {
We likely have a responsibility to throw an exception when any of the tag combos is out of spec. Here's the latest from the ANS-104 spec (https://github.com/joshbenaron/arweave-standards/blob/ans104/ans/ANS-104.md#21-verifying-a-dataitem):
```
A tag object is valid iff.:
• there are <= 128 tags
• each key is <= 1024 bytes
• each value is <= 3072 bytes
• only contains a key and value
• both the key and value are non-empty strings
```
We'll need to enforce these rules, with some new types and/or new logic here.

2021-12-14 23:02 UTC, arielmelendez commented on src/ardrive.ts
> -		private readonly bundle: boolean = true,
That's not so intuitive based on the class name. Let's strategize about that.

2021-12-14 23:09 UTC, arielmelendez commented on src/ardrive.ts
> +		/** @deprecated appName is now always read from ArFSTagBuilder */
Note: If it's always read from the ArFSTagBuilder, and if the tag builder and cost estimator are required, then we've effectively broken this API and it is no longer backwards compatible. Is it possible to add this architectural change without disrupting backwards compatibility?

2021-12-14 23:10 UTC, arielmelendez commented on src/arfs/arfs_tag_builder.test.ts
> +describe('ArFSTagBuilder class', () => {
Or maybe ArFSTagSettings?

2021-12-14 23:25 UTC, arielmelendez commented on src/arfs/arfsdao.ts
> +		protected readonly arFSTagBuilder: ArFSTagBuilder
Same comment here about breaking backwards compatibility.

2021-12-14 23:28 UTC, arielmelendez commented on src/arfs/arfsdao.ts
> +			if (!excludedTagNames.includes('Boost')) {
Oooh that's a tricky case.

2021-12-14 23:30 UTC, arielmelendez commented on src/arfs/arfsdao.ts
> +			if (!excludedTagNames.includes('Boost')) {
Could it make more sense to push it onto "otherTags" and then use the tags builder down below and let it get filtered out by `withBaseBundleTags`?

2021-12-14 23:30 UTC, arielmelendez commented on src/arfs/arfsdao.ts
> +		const tags = this.arFSTagBuilder.withBaseArFSTags([...objectMetaData.gqlTags, ...otherTags], excludedTagNames);
Same comments as above about moving this down below the scope of the boost checks.

2021-12-14 23:34 UTC, arielmelendez commented on src/arfs/arfsdao_anonymous.ts
> +		protected readonly arFSTagBuilder: ArFSTagBuilder
Same comments about backwards compatibility.

2021-12-15 01:12 UTC, arielmelendez commented on src/types/cost_estimator_types.ts
> +	// TODO: Add Bundle Plan { numOfBundles: number , ... }
Is this still todo?

2021-12-15 01:16 UTC, arielmelendez commented on src/ardrive_factory.ts
> +	bundle = true,
bundle sounds like a noun. Consider `shouldBundle`

2021-12-15 01:26 UTC, arielmelendez requested changes
Left a number of important comments. Let's circle up if you have questions or concerns.

2021-12-15 02:17 UTC, fedellen commented on src/ardrive.ts
> +		/** @deprecated appName is now always read from ArFSTagBuilder */
Hmm. We could probably achieve this by making the new fields optional and use the constructor to supply the defaults. That way we have access to the appVersion/appName 

I'll try some things out

2021-12-15 22:28 UTC, fedellen commented on src/ardrive.ts
> -		private readonly bundle: boolean = true,
Haven't renamed the `ArFSCostEstimator` class yet. Maybe `ArFSWriteOperationPreparer` or similar?

2021-12-15 22:29 UTC, fedellen commented on src/ardrive_factory.ts
> +	arFSTagBuilder = new ArFSTagSettings({ appName, appVersion }),
This var escaped rename

2021-12-16 21:20 UTC, arielmelendez commented on src/ardrive.ts
> -		private readonly bundle: boolean = true,
ArFSUploadPlanner? I think a lot of what we talk about when prepping uploads is planning.

2021-12-16 21:46 UTC, arielmelendez commented on src/pricing/arfs_cost_estimator.ts
> +			this.arFSTagSettings.assembleBaseArFSTags({ tags: objectPrototype.gqlTags })
This is ok, but there's some "fluent interface" readability opportunities here with the addition of the object params, e.g.:
```
			this.arFSTagSettings.baseTagsIncluding({ tags: objectPrototype.gqlTags })
```
or
```
			this.arFSTagSettings.baseTagsIncluding({ otherTags: objectPrototype.gqlTags })
```

2021-12-16 21:51 UTC, arielmelendez commented on src/pricing/arfs_cost_estimator.ts
> +			this.arFSTagSettings.assembleBaseArFSTags({ tags: objectPrototype.gqlTags })
or:
```
this.arFSTagSettings.baseTags({ includingTags: objectPrototype.gqlTags, excludingTagsNamed: ['foo'] })
```

2021-12-16 21:54 UTC, arielmelendez commented on src/arfs/arfs_tag_settings.test.ts
> +		it('throws an error if the name field is not a string', () => {
```suggestion
		it('throws an error if the value field is not a string', () => {
```

2021-12-16 21:54 UTC, arielmelendez commented on src/arfs/arfs_tag_settings.test.ts
> +		it('throws an error if the name field is an empty string', () => {
```suggestion
		it('throws an error if the value field is an empty string', () => {
```

2021-12-16 21:59 UTC, arielmelendez commented on src/arfs/arfs_tag_settings.test.ts
> +		it('throws an error if there are too many GQL tags', () => {
Please add the negative of this test as well right at the limit, i.e. 128 tags.

2021-12-16 22:00 UTC, arielmelendez commented on src/arfs/arfs_tag_settings.test.ts
> +		it('throws an error if the name field on a tag has too many bytes', () => {
Please add the negative of this test as well right at the limit, i.e. 1024 bytes.

2021-12-16 22:00 UTC, arielmelendez commented on src/arfs/arfs_tag_settings.test.ts
> +		it('throws an error if the value field on a tag has too many bytes', () => {
Please add the negative of this test as well right at the limit, i.e. 3072 bytes.

2021-12-16 22:01 UTC, arielmelendez requested changes
Left a handful of test requests, typo fix suggestions, and potential naming update suggestions.

2021-12-17 02:56 UTC, arielmelendez approved these changes

2021-12-17 03:01 UTC, merged