PE-880: implement the ArFSDAO methods to send the rename tx
ardriveapp/ardrive-core-js pull request #124
Opened 2022-01-14 17:13 UTC by matibat

2022-01-17 21:30 UTC, fedellen commented on src/arfs/arfsdao.ts
> +		};
Usually, we construct this return at the ArDrive layer. I don't really see a problem doing it here instead, but we do need to construct the `fees` information here as well:

```suggestion
		return {
			created: [{ type: 'file', metadataTxId: new TransactionID(metaDataTx.id), entityId: publicFile.entityId }],
			tips: [],
			fees: { [metaDataTx.id]: metaDataTx.reward }
		};
```

2022-01-17 21:43 UTC, fedellen requested changes
See comment, we must have the fee information for the metadata tx preserved at this level

2022-01-17 21:52 UTC, fedellen commented on src/arfs/arfsdao.ts
> +		};
I just realized we should also be preserving the `dataTxId` information and the `key` information on private renames

2022-01-18 16:04 UTC, matibat commented on src/arfs/arfsdao.ts
> +		};
I think this would do the thing: 1c323634ffb220accff6de0706a0f2609221a8a3
Unless the `key` information refers to something else

2022-01-18 16:38 UTC, fedellen commented on src/arfs/arfsdao.ts
> +		};
The `key` info in this case is the fileKey. We send it back with private upload-file and also private move-file.

So to remain consistent, in the `created` type on private we should add: `key: urlEncodeHashKey(privateFile.fileKey)`

We also return the `dataTxId` on both public and private files in the same `created` object type: `dataTxId: publicFile.dataTxId`

2022-01-18 20:13 UTC, fedellen commented on src/arfs/arfsdao.ts
> +		const fileKey: FileKey = await deriveFileKey(`${privateFile.fileId}`, driveKey);
Haven't pulled this down, but I believe the fileKey is available on `metadataTxData.fileKey` or `fileMetadata.objectData.fileKey` here.

2022-01-18 20:13 UTC, fedellen commented on src/arfs/arfsdao.ts
> +		};
Nice updates! Resolving this

2022-01-19 18:24 UTC, matibat commented on src/arfs/arfsdao.ts
> +		const fileKey: FileKey = await deriveFileKey(`${privateFile.fileId}`, driveKey);
I've found the file key inside `fileMetadataTxData.fileKey`: 06c6ad2e57c01a081456b4aafdd94f3c5906db80

2022-01-20 01:36 UTC, arielmelendez commented on src/arfs/arfs_entity_result_factory.ts
> +export interface ArFSRenameFileResult extends ArFSRenameEntityResult {
Funny type. It's called a "FileResult" and yet it bears an `EntityType` member... Also the other result data is a `FileID`, even though FileIDs don't change on a rename. Really interested to see how this gets used...

2022-01-20 01:58 UTC, arielmelendez commented on src/arfs/arfsdao.ts
> +		fileId,
I think this API gets a lot tidier if you just take an ArFSPublicFile. Then you don't need the fileId or owner. Let the ArDrive layer use the DAO to do the fetching.

2022-01-20 02:02 UTC, arielmelendez commented on src/arfs/arfsdao.ts
> +		fileId,
Same here. This gets tidier if you just take an ArFSPrivateFile.

2022-01-20 02:45 UTC, arielmelendez requested changes
Left a few design comments here that percolated out to the ArDrive layer in the next PR.

2022-01-20 18:15 UTC, matibat commented on src/arfs/arfs_entity_result_factory.ts
> +export interface ArFSRenameFileResult extends ArFSRenameEntityResult {
Cleanup: 1badad2

2022-01-20 18:15 UTC, matibat commented on src/arfs/arfsdao.ts
> +		fileId,
Cleanup: 1badad2

2022-01-20 18:16 UTC, matibat commented on src/arfs/arfsdao.ts
> +		fileId,
Cleanup: 1badad2

2022-01-20 18:20 UTC, fedellen approved these changes

2022-01-20 21:59 UTC, arielmelendez commented on src/arfs/arfsdao.ts
> +			metaDataTxId: new TransactionID(metaDataTx.id),
Nit: You can use the TxID convenience function.

2022-01-20 22:00 UTC, arielmelendez approved these changes

2022-01-21 12:26 UTC, matibat commented on src/arfs/arfsdao.ts
> +			metaDataTxId: new TransactionID(metaDataTx.id),
Nice catch! 73a9d1b

2022-01-21 12:27 UTC, merged