PE-881: Implement the ArDrive methods for rename
ardriveapp/ardrive-core-js pull request #125
Opened 2022-01-14 17:31 UTC by matibat

2022-01-17 21:26 UTC, fedellen commented on src/ardrive.ts
> +	}
This API seems to be a significant change from the rest of the ArDrive layer methods. We're requiring the file entity itself here as well as rewardSettings which we haven't previously exposed.

I would suggest a very simple API, `fileId`, `newName`, and `driveKey`. This would be consistent with the moveFile/moveFolder APIs and would generally be less confusing for a a dev trying to integrate with ArDrive Core.

Also, there seems to be a few steps missing here including:
- Asserting the owner of the drive
- Determining the reward for the transaction
- Asserting the balance of the wallet

2022-01-19 02:22 UTC, fedellen commented on src/ardrive.ts
> +	async estimateAndAssertCostOfFileRename(metaData: ArFSObjectTransactionData): Promise<MetaDataBaseCosts> {
Looks like we can probably re-use the same estimation logic here for both folder creation and move file. If so, we can rename this to something like `estimateAndAssertCostOfMetaDataTx` and excise the other two estimate and assert methods: `estimateAndAssertCostOfFolderUpload` and `estimateAndAssertCostOfMoveFile`.

I would also make this method `private` as I don't think we intend for these estimation methods to be immediately public facing

2022-01-19 02:24 UTC, fedellen commented on src/ardrive.ts
> +	async renamePublicFile({ fileId, newName, owner }: RenamePublicFileParams): Promise<ArFSResult> {
We could use some integration tests for these new methods. It would provide coverage for both the ArDrive and ArFSDAO layers.

I'd be happy to huddle up tomorrow to get this started

2022-01-19 18:42 UTC, matibat commented on src/ardrive.ts
> +	async estimateAndAssertCostOfFileRename(metaData: ArFSObjectTransactionData): Promise<MetaDataBaseCosts> {
Great idea! 5b91164cc7cf4da98f03710799adf64496010fee

2022-01-20 02:37 UTC, arielmelendez commented on src/ardrive.ts
> +		await assertValidArFSFileName(newName);
no need to await

2022-01-20 02:42 UTC, arielmelendez commented on src/ardrive.ts
> +					type: result.type,
So as pointed out in the other PR, you don't need an entity type in the result type. We know that we are working with a file by way of the APIs we're in.

2022-01-20 02:44 UTC, arielmelendez commented on src/ardrive.ts
> +	async renamePublicFile({ fileId, newName, owner }: RenamePublicFileParams): Promise<ArFSResult> {
Same comment as in the ArFSFDao PR - make this easier to use correctly and just eliminate the owner from the input params. You've already configured the ArDrive class with the wallet when it was created so the owner shouldn't be allowed to be passed in here. It should be fetched from on chain for the fileId passed in like so:
```
async renamePublicFile({ fileId, newName }: RenamePublicFileParams): Promise<ArFSResult> {
		const owner = await this.arFsDao.getDriveOwnerForFileId(fileId);
		await this.assertOwnerAddress(owner);
```

2022-01-20 02:45 UTC, arielmelendez commented on src/ardrive.ts
> +		await assertValidArFSFileName(newName);
no need to await here

2022-01-20 02:45 UTC, arielmelendez requested changes
Make APIs easier to use correctly.

2022-01-20 18:20 UTC, matibat commented on src/ardrive.ts
> +	}
Going back to here:
 1. The owner of the drive is asserted at the `getPrivateFile` (or public) method
 2. The reward of the transaction is now being returned
 3. There's now a function for asserting the wallet balance before triggering the rename

And the parameters were cleaned up

2022-01-20 18:21 UTC, matibat commented on src/ardrive.ts
> +	async renamePublicFile({ fileId, newName, owner }: RenamePublicFileParams): Promise<ArFSResult> {
Added at #132

2022-01-20 18:25 UTC, matibat commented on src/ardrive.ts
> +	async renamePublicFile({ fileId, newName, owner }: RenamePublicFileParams): Promise<ArFSResult> {
I removed the `owner` param; although instead of checking the owner here, it's already enforced at the `getPrivateFile` and `getPublicFile` methods

2022-01-20 18:26 UTC, matibat commented on src/ardrive.ts
> +		await assertValidArFSFileName(newName);
9fd5eb7

2022-01-20 18:26 UTC, matibat commented on src/ardrive.ts
> +		await assertValidArFSFileName(newName);
9fd5eb7

2022-01-20 18:27 UTC, fedellen approved these changes
Great updates!

2022-01-20 18:31 UTC, matibat commented on src/ardrive.ts
> +					type: result.type,
For the `created` type structure (i.e. `ArFSEntityData[]`) we have we enforce a non-nullable `type` property. So I hardcoded it as `"file"` now.
There's no longer a `result.type`

2022-01-20 22:09 UTC, arielmelendez commented on src/ardrive.ts
> +	async renamePublicFile({ fileId, newName, owner }: RenamePublicFileParams): Promise<ArFSResult> {
Those methods `getPublic/PrivateFile` FETCH the owner, but do not ENFORCE that the owner is the same as the owner of the configured wallet for the ArDrive class. You will need to enforce the ownership.

2022-01-20 22:10 UTC, arielmelendez requested changes
Must enforce ownership

2022-01-20 22:20 UTC, fedellen commented on src/ardrive.ts
> +	async renamePublicFile({ fileId, newName, owner }: RenamePublicFileParams): Promise<ArFSResult> {
Ah, good catch. Looks like `getPrivateFile` method does enforce the ownership:

```ts
	public async getPrivateFile({ fileId, driveKey, owner }: GetPrivateFileParams): Promise<ArFSPrivateFile> {
		if (!owner) {
			owner = await this.arFsDao.getDriveOwnerForFileId(fileId);
		}
		await this.assertOwnerAddress(owner);

		return this.arFsDao.getPrivateFile(fileId, driveKey, owner);
	}
```

 But not the `getPublicFile` method, as it resides in the anonymous class which does not have a wallet to assert against:
 
 ```ts
 	public async getPublicFile({ fileId, owner }: GetPublicFileParams): Promise<ArFSPublicFile> {
		if (!owner) {
			owner = await this.arFsDao.getDriveOwnerForFileId(fileId);
		}

		return this.arFsDao.getPublicFile(fileId, owner);
	}
 ```

2022-01-21 08:23 UTC, arielmelendez commented on src/ardrive.ts
> +	async renamePublicFile({ fileId, newName, owner }: RenamePublicFileParams): Promise<ArFSResult> {
`getPrivateFile` should not be enforcing ownership. If you have a driveKey, then it doesn't matter if you have the wallet or not. We haven't thought of this as a problem yet, I believe, because we don't allow for creating the ArDrive class without a wallet, and that has trickled its way up to the CLI layer and we have just lived with the consequence on needing a wallet even when we have keys provided (I believe there's a story or defect open to make this issue go away). I'd advise removing the owner assertion from `getPrivateFile` and moving that function down into the anonymous ardrive class as a baby step towards fixing the other ticket. The ownership assertions should happen during write functions only, if we can manage that.

2022-01-21 12:20 UTC, matibat commented on src/ardrive.ts
> +	async renamePublicFile({ fileId, newName, owner }: RenamePublicFileParams): Promise<ArFSResult> {
Let's see here: 4a449566dee00c557250c80be5b88095e7661e9d

2022-01-21 16:57 UTC, arielmelendez approved these changes

2022-01-21 16:59 UTC, merged