PE-896: Implement methods for rename-folder ArDrive
ardriveapp/ardrive-core-js pull request #136
Opened 2022-01-25 15:01 UTC by matibat

2022-01-26 00:12 UTC, arielmelendez commented on src/arfs/arfs_entity_name_validators.ts
> +export function assertValidArFSEntityName(entityType: 'file' | 'folder', name: string): boolean {
@karlprieb just a heads up that this will likely be the branch you'll want to branch from for your upcoming ticket.

2022-01-26 00:13 UTC, arielmelendez commented on src/arfs/arfs_entity_name_validators.ts
> +export const assertValidArFSFileName = assertValidArFSEntityName.bind(this, 'file');
Is binding strictly necessary?

2022-01-26 00:14 UTC, arielmelendez commented on src/ardrive.ts
> +				`The root folder cannot be renamed as it shares name with their drive. Try renaming the drive instead`
```suggestion
				`The root folder cannot be renamed as it shares its name with its parent drive. Consider renaming the drive instead.`
```

2022-01-26 00:17 UTC, arielmelendez commented on src/ardrive.ts
> +			throw new Error(`To rename a folder, the new name must be different`);
```suggestion
			throw new Error(`New folder name '${newName}' must be different from the current folder name!`);
```

2022-01-26 00:17 UTC, arielmelendez commented on src/ardrive.ts
> +			throw new Error(`To rename a folder, the new name must be different`);
Apply this in the public example as well.

2022-01-26 00:17 UTC, arielmelendez commented on src/ardrive.ts
> +				`The root folder cannot be renamed as it shares name with their drive. Try renaming the drive instead`
Apply this in the public example as well.

2022-01-26 00:21 UTC, arielmelendez requested changes
Looks good! Just had some minor suggestions around error messages.

2022-01-26 00:56 UTC, karlprieb commented on src/arfs/arfs_entity_name_validators.ts
> +export function assertValidArFSEntityName(entityType: 'file' | 'folder', name: string): boolean {
👍 I linked this branch on the ticket description.

2022-01-26 17:26 UTC, matibat commented on src/arfs/arfs_entity_name_validators.ts
> +export const assertValidArFSFileName = assertValidArFSEntityName.bind(this, 'file');
It is not. I'm gonna refactor the function to use the factory pattern instead

2022-01-26 17:30 UTC, matibat commented on src/ardrive.ts
> +				`The root folder cannot be renamed as it shares name with their drive. Try renaming the drive instead`
922e931a66c06ce8bde2ddd2a4dd90bee3c79cdc

2022-01-26 17:30 UTC, matibat commented on src/ardrive.ts
> +			throw new Error(`To rename a folder, the new name must be different`);
922e931a66c06ce8bde2ddd2a4dd90bee3c79cdc

2022-01-26 17:33 UTC, matibat commented on src/arfs/arfs_entity_name_validators.ts
> +export const assertValidArFSFileName = assertValidArFSEntityName.bind(this, 'file');
Like so: d1db818261c324f0dd3e9092ea5b9852763cf84c

2022-01-26 17:39 UTC, matibat commented on src/arfs/arfs_entity_name_validators.ts
> +export const assertValidArFSFileName = assertValidArFSEntityName.bind(this, 'file');
Added also the missing tests for the `assertValidArFSFolderName` method: 78e710cdc6ffcf25b0b3b7d794daa9e79e93b202

2022-01-27 16:17 UTC, arielmelendez commented on src/arfs/arfs_entity_name_validators.ts
> +export function assertValidArFSEntityNameFactory(entityType: 'file' | 'folder'): (name: string) => boolean {
Is it truly necessary for this to be a factory function? Can it not just take entityType and name as input parameters? My worry is that calling this in a tight loop would thrash the heap while creating and destroying function objects over and over again rather than just using the one loaded into the namespace. Not the end of the world but just seems more efficient to not allocate something new each time.

2022-01-27 16:18 UTC, arielmelendez approved these changes

2022-01-27 16:54 UTC, matibat commented on src/arfs/arfs_entity_name_validators.ts
> +export function assertValidArFSEntityNameFactory(entityType: 'file' | 'folder'): (name: string) => boolean {
If you are talking about **multiple instances** of the CLI, then you are right, the factory function will be called three times for each instance. In the other side, if you are talking about the same instance, then we are fine: the funcion is called once per entity type the first time the module is loaded.

2022-01-27 17:20 UTC, merged