PE-970: Implement ArFSPrivateFileOrFolderWithPathsAndKeys
ardriveapp/ardrive-core-js pull request #153
Opened 2022-02-04 12:32 UTC by matibat

Sub-task of PE-771: Add fileKey / driveKey to private list commands

2022-02-07 22:22 UTC, matibat commented
The unit tests for the newly implemented class are at #156 and #157

2022-02-09 16:27 UTC, arielmelendez commented on src/arfs/arfs_entities.ts
> +	readonly fileKey?: string;
Really want to avoid this pattern if possible. Handle optionality down in the builders and at higher levels try downcasting to the type that will definitely have the fileKey if needed.

2022-02-09 18:51 UTC, matibat commented on src/arfs/arfs_builders/arfs_file_builders.ts
> +					break;
This doesn't belong here. It is removed at #154

2022-02-09 22:11 UTC, matibat commented on src/arfs/arfs_builders/arfs_file_builders.ts
> +	fileKey: string;
This guy where removed

2022-02-09 22:12 UTC, matibat commented on src/arfs/arfs_entities.ts
> +	get fileKey(): FileKey {
The getter went away. Now the ArFSPrivateFile will hold its `fileKey` since built

2022-02-10 11:50 UTC, matibat commented
### Files with path refactored

Initially, there was `ArFSPublicFileOrFolderWithPaths` as the generic for any File or Folder regardless of its privacy. Now, the requirements specify the need to display the keys associated to each **private** entity.

#### For Public entities
- `ArFSPublicFolderOrFileWithPaths` is the generic for any Public Folder or File as it extends the generic `ArFSFileOrFolderEntity`.

#### For Private entities
- There is a specific `ArFSPrivateFolderWithPaths` which now holds an extra `driveKey` member, and extends the `ArFSFileOrFolderEntity` at the point above.
  - `ArFSPrivateFolderWithPathsKeyless` is a wrapper which hides the `driveKey`.
- And `ArFSPrivateFileWithPaths` extending `ArFSPrivateFolderWithPaths`, which declares another extra member `fileKey`, which is taken at the constructor from the passed ArFSPrivateFile.
  - `ArFSPrivateFileWithPathsKeyless` is a wrapper that hides the `driveKey` and `fileKey`.

#### Changes on entities
- For us to have access to the file keys without having to derivate it each time, the `ArFSPrivateFile` now holds its `fileKey` since build time. Given that some commands print the whole content of this class directly to the user -and that would change the current behavior- a new `ArFSPrivateFileKeyless` was declared for those specific cases.
- No changes were required for the `ArFSPrivateFolder` nor any public class.

2022-02-10 14:00 UTC, karlprieb commented on src/ardrive_anonymous.ts
> +	}: ListPublicFolderParams): Promise<ArFSPublicFolderOrFileWithPaths[]> {
I saw that we have two different ways to deal with "FolderOrFileWithPaths", for private one you don't use `ArFSPrivateFileOrFolderWithPaths` anymore, instead you're using `ArFSPrivateFolderWithPaths | ArFSPrivateFileWithPaths`, which I think it's great.
Why not follow the same pattern for `ArFSPublicFolderOrFileWithPaths`?

2022-02-10 14:04 UTC, karlprieb commented on src/arfs/arfs_entities.ts
> +		appName: string,
Why are you removing `readonly`, are we reassigning these values in another place?

2022-02-10 15:26 UTC, matibat commented on src/arfs/arfs_entities.ts
> +		appName: string,
Exactly, that's why: the class inherits these properties from the parent class (e.i. `ArFSFileOrFolderEntity` in this case) which are already read-only. But having in mind this change isn't actually required on the spec, we might want to un-do it :thinking:

2022-02-11 15:27 UTC, matibat commented on src/ardrive_anonymous.ts
> +	}: ListPublicFolderParams): Promise<ArFSPublicFolderOrFileWithPaths[]> {
The class were split on the upcoming PR: #156 
At this point, it had no difference because we were using the `entityId` as a generic version of the specific `folderId` and `fileId` of Folder and File respectively. Now separarted.

2022-02-11 15:49 UTC, matibat commented on src/ardrive_anonymous.ts
> +	}: ListPublicFolderParams): Promise<ArFSPublicFolderOrFileWithPaths[]> {
Just cherry-picked the commit into here
```
git cherry-pick f916da861f10122d63524cf5bcc9b6cd19e07190
```

2022-02-11 16:06 UTC, matibat reviewed
**Q** for the reviewer
Should I re-add the `readonly` modifier to the entities constructor argument? That would make the arguments transform into properties (which is already done at the parent classes through inheritance) ovewriting the already set values.

2022-02-11 16:06 UTC, matibat commented on src/arfs/arfs_entities.ts
> +export class ArFSPublicFolderWithPaths extends ArFSFileOrFolderEntity {
Is `WithPath` no longer in use? If so: do we want to make use of it? or delete the interface?

2022-02-11 16:07 UTC, matibat commented on src/arfs/arfs_entities.ts
> +export class ArFSPublicFolderWithPaths extends ArFSFileOrFolderEntity {
We DO want to make use of it.

2022-02-11 16:32 UTC, matibat commented on src/arfs/arfs_entities.ts
> +export class ArFSPublicFolderWithPaths extends ArFSFileOrFolderEntity {
Applied here: bbd81edf7140b4cf400a5592808df33a8cdc5d16

2022-02-11 16:46 UTC, fedellen commented on src/arfs/arfs_entities.ts
> +		return new ArFSPrivateFileWithPaths(entityAsFile, hierarchy, driveKey);
Not sure if this makes sense in the flow here, but I think  it makes sense to have `ArFSPrivateFolder` just have the `entityType` field defined as `'folder'` rather than `EntityType` and the same with `ArFSPrivateFile` defining it as `'file'`. 

This would make the `as` casting here unnecessary and the compiler would be able to narrow the types based solely on `entity.entityType === XX`

2022-02-11 16:50 UTC, fedellen commented on src/arfs/arfs_entities.ts
> +		return new ArFSPrivateFileWithPaths(entityAsFile, hierarchy, driveKey);
Could be a complicated type battle though with passing the value through the constructors

2022-02-11 16:58 UTC, fedellen commented on src/arfs/arfs_builders/arfs_file_builders.ts
> +					break;
I don't see this in the diff at #154. Can we just clean it up here?

2022-02-11 18:27 UTC, matibat commented on src/arfs/arfs_entities.ts
> +		return new ArFSPrivateFileWithPaths(entityAsFile, hierarchy, driveKey);
Woah! Thank you so much!
I'm happy with the results: the factories are now much cleaner
84ccf07be40f16c372f49bf05df0c7899587138c

2022-02-11 18:31 UTC, fedellen commented on src/arfs/arfs_entities.ts
> +		return new ArFSPrivateFileWithPaths(entityAsFile, hierarchy, driveKey);
Will probably need to sanitize or cast these in the `arfs_builder` layer to account for the type change

2022-02-11 18:37 UTC, matibat commented on src/arfs/arfs_entities.ts
> +		return new ArFSPrivateFileWithPaths(entityAsFile, hierarchy, driveKey);
You are right: 006eeb57eeba6a021c16e8b5e703d7785318568c

2022-02-12 00:19 UTC, matibat commented on src/arfs/arfs_builders/arfs_file_builders.ts
> +		readonly owner?: ArweaveAddress
Add `fileKey` back again

2022-02-12 00:34 UTC, matibat commented on src/arfs/arfs_builders/arfs_file_builders.ts
> +		readonly owner?: ArweaveAddress
Add `fileKey` back again
```suggestion
		readonly owner?: ArweaveAddress,
		readonly fileKey?: FileKey
```

2022-02-14 19:50 UTC, fedellen approved these changes

2022-02-15 22:46 UTC, arielmelendez commented on src/arfs/arfs_entities.ts
> +	if (entity.entityType === 'folder') {
This is an example of a place where I'd use a switch in case more entity types are added in the future.

2022-02-15 22:48 UTC, arielmelendez commented on src/arfs/arfs_entities.ts
> +	constructor(entity: ArFSPrivateFolder, hierarchy: FolderHierarchy, driveKey: DriveKey) {
I don't like the separation of the driveKey from the ArFSPrivateFolder object here.

2022-02-15 22:50 UTC, arielmelendez commented on src/arfs/arfs_entities.ts
> +	constructor(entity: ArFSPrivateFile, hierarchy: FolderHierarchy, driveKey: DriveKey) {
Similar to the above, I don't like the separation of the driveKey and fileKey from the ArFSPrivateFile object. As a result you have duplicated key derivation logic below.

2022-02-15 22:52 UTC, arielmelendez commented on src/arfs/arfs_entities.ts
> +		this.driveKey = urlEncodeHashKey(driveKey);
Why is it necessary to urlEncode these on the way in? Perhaps a property getter is necessary that performs that transformation of the raw data on read. As is, this to me is creating the problem of having the same data in 2 places AND is creating confusion for the reader about the expected format of this data.

2022-02-16 07:10 UTC, arielmelendez commented on src/arfs/arfs_entities.ts
> +	constructor(entity: ArFSPrivateFolder, hierarchy: FolderHierarchy, driveKey: DriveKey) {
I feel strongly that we need to avoid this if possible.

2022-02-16 07:11 UTC, arielmelendez requested changes
Drive key should be stored in the entity type on construction and used elsewhere rather than passing it around separately in many places.

2022-02-16 13:49 UTC, matibat commented on src/arfs/arfs_entities.ts
> +		this.driveKey = urlEncodeHashKey(driveKey);
I will try instead to add a `toJson` for DriveKey and FileKey. If that creates unwanted conflicts, I'll try adding it to the entities' constructor itself.

The only reason it was represented as a string here is for `JSON.stringify` to do not treat them as a Buffer object

2022-02-16 13:51 UTC, matibat commented on src/arfs/arfs_entities.ts
> +	constructor(entity: ArFSPrivateFolder, hierarchy: FolderHierarchy, driveKey: DriveKey) {
This is because I didn't apply this same change to `ArFSPrivateFolder` (as I did for `ArFSPrivateFile` with `fileKey`). I'm gonna apply it as well

2022-02-16 14:02 UTC, matibat commented on src/arfs/arfs_entities.ts
> +	if (entity.entityType === 'folder') {
It seems the typing of Typescript gives us the same safety as `Swift`'s `switch..case`. Here Typescript says: "Alright, `entity` is `ArFSPublicFolder` or `ArFSPublicFile`", then it enters the condition saying: "if this entity has the property `entityType` with value `'folder'`, then it must be an `ArFSPublicFolder`", and when it doesn't enter the condition it says: "hmmm, the entity type of this one is not `'folder'`, then the only left case is `entity` being an `ArFSPublicFile`".

This fabulous behavior came after I applied [the change suggested here](https://github.com/ardriveapp/ardrive-core-js/pull/153#discussion_r804829139) which made the types to be more strict. I.e. previously the builders would create a Folder regardless of what their `entityType` was, now it throws if it mismatches with the **only** allowed value for folders.

2022-02-16 14:56 UTC, matibat commented on src/arfs/arfs_entities.ts
> +	constructor(entity: ArFSPrivateFolder, hierarchy: FolderHierarchy, driveKey: DriveKey) {
Applied: [fd475fa](https://github.com/ardriveapp/ardrive-core-js/pull/153/commits/fd475fa775741545ef211d43b9b5280fc65fda44)

2022-02-16 14:56 UTC, matibat commented on src/arfs/arfs_entities.ts
> +	constructor(entity: ArFSPrivateFile, hierarchy: FolderHierarchy, driveKey: DriveKey) {
Applied: [fd475fa](https://github.com/ardriveapp/ardrive-core-js/pull/153/commits/fd475fa775741545ef211d43b9b5280fc65fda44)

2022-02-16 20:52 UTC, arielmelendez commented on src/arfs/arfs_builders/arfs_drive_builders.ts
> +				return new ArFSPrivateDriveKeyless(
I think we could decide whether to return ArFSPrivateDrive vs. ArFSPrivateDriveKeyless based on whether there is a workable driveKey for it (i.e. anything is returned from `this.privateKeyData.driveKeyForDriveId(this.driveId)`) and/or whether the dataJSON matches the placeholder values (i.e. decryption didn't work out).

2022-02-16 20:55 UTC, arielmelendez commented on src/arfs/arfs_builders/arfs_drive_builders.ts
> +				return new ArFSPrivateDriveKeyless(
My worry about always sending back a keyless one is that you then can't use this API to get back full drives when you do indeed have keys.

2022-02-16 20:56 UTC, arielmelendez commented on src/arfs/arfs_builders/arfs_file_builders.ts
> +				!(this.entityType === 'file')
Seems like a good check, but wondering whether it was strictly necessary based on changes made elsewhere?

2022-02-16 21:23 UTC, arielmelendez commented on src/arfs/arfs_entities.ts
> +		readonly driveKey: DriveKey
It could make sense to throw in the constructor if the FileKey doesn't match what's expected when the DriveKey and FileID are provided... I'm not sure if it's worth the computational overhead, though, since the builders are already being trusted to provide good values here.

2022-02-16 21:23 UTC, arielmelendez commented on src/arfs/arfs_entities.ts
> +	// toJson(): string {
Should this comment be removed?

2022-02-16 21:23 UTC, arielmelendez commented on src/arfs/arfs_entities.ts
> +	// toJson(): string {}
Should this comment be removed?

2022-02-16 21:33 UTC, arielmelendez commented on src/arfs/arfs_entities.ts
> +		readonly folderId: FolderID,
Don't create memory for folderId.

2022-02-16 21:35 UTC, arielmelendez requested changes
Good updates. See my comments.

2022-02-17 00:30 UTC, matibat commented on src/arfs/arfs_builders/arfs_file_builders.ts
> +				!(this.entityType === 'file')
Yes. This came up after ArFSFileEntity had `entityType: 'file'` (instead of `EntityType`). See here: 84ccf07be40f16c372f49bf05df0c7899587138c

2022-02-17 00:31 UTC, matibat commented on src/arfs/arfs_entities.ts
> +	// toJson(): string {
This should be implemented at `ArFSEntity` (TODO)

2022-02-17 00:32 UTC, matibat commented on src/arfs/arfs_entities.ts
> +	// toJson(): string {}
Same than above

2022-02-17 00:34 UTC, matibat commented on src/arfs/arfs_builders/arfs_drive_builders.ts
> +				return new ArFSPrivateDriveKeyless(
Y should check for the presence of the `driveKey` to conditionally return normal vs keyless

2022-02-17 02:33 UTC, jdaev commented on src/arfs/arfs_file_wrapper.ts
> +		public readonly folderToGenManifest: (ArFSPublicFolderWithPaths | ArFSPublicFileWithPaths)[],
Why would you need to generate a manifest from ArFSPublicFileWithPaths? Isn't it always going to be a folder?

2022-02-17 06:51 UTC, arielmelendez commented on src/arfs/arfs_builders/arfs_drive_builders.ts
> +				return new ArFSPrivateDriveKeyless(
Is that a question? 🧐😬

2022-02-17 11:15 UTC, matibat commented on src/arfs/arfs_builders/arfs_drive_builders.ts
> +				return new ArFSPrivateDriveKeyless(
Nono, a statement. Thank you :)

2022-02-17 11:16 UTC, matibat commented on src/arfs/arfs_file_wrapper.ts
> +		public readonly folderToGenManifest: (ArFSPublicFolderWithPaths | ArFSPublicFileWithPaths)[],
I think you are right! @fedellen do you agree?

2022-02-17 11:54 UTC, matibat commented on src/arfs/arfs_entities.ts
> +		readonly folderId: FolderID
Let's also cache the entity IDs at the constructor so it returns the same instance for the same value. That would in fact also fix the equality operator: by returning the same instance at construction time `new EID(idAsString) === EID(idAsString)`. What do you think?

2022-02-17 11:55 UTC, matibat commented on src/arfs/arfs_entities.ts
> +		readonly folderId: FolderID
And for this particular case, we shouldn't care about memory because it is well managed by the EntityID constructor. We will be using pointers to the same data always

2022-02-17 13:01 UTC, matibat commented on src/arfs/arfs_entities.ts
> +		readonly folderId: FolderID
Drafting...
```ts
		private static cache: Map<string, EntityID> = new Map();

		// constructor(entityId: string) {
		// const cachedEID = EntityID.cache.get(entityId);
		// if (!cachedEID) {
		// 	EntityID.cache.set(entityId, this);
		// 	return this;
		// }
		// return cachedEID;
```

2022-02-17 15:01 UTC, matibat commented on src/arfs/arfs_entities.ts
> +	// toJson(): string {
Created a wrapper class for the buffer data of the keys (`EntityKey`) which implements a custom `toJSON` in order for it to be interpreted as the URL-encoded version of the key. [8b4a7d6](https://github.com/ardriveapp/ardrive-core-js/pull/153/commits/8b4a7d61f00503e2f2294d7337d1ba4a9060ebc8)

2022-02-17 15:11 UTC, matibat commented on src/arfs/arfs_entities.ts
> +		readonly folderId: FolderID
As we are passing exactly the same instance to the parent class as given, those are two aliases pointing to the same in-memory data. No extra memory will be reserved in this case.

2022-02-17 15:13 UTC, matibat commented on src/arfs/arfs_entities.ts
> +		readonly folderId: FolderID
Also, by using a getter, JSON.stringify wouldn't be able to read it (which may be what we want). What's `readonly` making here is to declare a new attribute.

2022-02-17 15:18 UTC, fedellen commented on src/arfs/arfs_file_wrapper.ts
> +		public readonly folderToGenManifest: (ArFSPublicFolderWithPaths | ArFSPublicFileWithPaths)[],
This constructor basically takes the output of a `listFolder` and turns it into a valid arweave manifest. To produce the manifest, you will absolutely need the `ArFSPublicFileWithPaths` as well as the target folder's `path`.

I think the variable name could more clearly indicate that.

2022-02-17 16:03 UTC, matibat commented on src/arfs/arfs_file_wrapper.ts
> +		public readonly folderToGenManifest: (ArFSPublicFolderWithPaths | ArFSPublicFileWithPaths)[],
So, it takes files and folders with paths: [9fbb5bd](https://github.com/ardriveapp/ardrive-core-js/pull/153/commits/9fbb5bd42a41cca191cf219fc6f47741ef0d5231)

2022-02-17 17:52 UTC, matibat commented on src/arfs/arfs_entities.ts
> +		readonly driveKey: DriveKey
Let's have that as a tech_debt ticket if we want the change :)

2022-02-17 17:52 UTC, matibat commented on src/arfs/arfs_entities.ts
> +		this.driveKey = urlEncodeHashKey(driveKey);
This outdated. Now EntityKey will return a string when stringified

2022-02-17 18:31 UTC, matibat reviewed
A couple of nit comments

2022-02-17 18:31 UTC, matibat commented on src/ardrive.ts
> +		createDriveResult.created[1].key = urlEncodeHashKey(newDriveData.driveKey.keyData);
```suggestion
		createDriveResult.created[0].key = newDriveData.driveKey.toJSON();
		createDriveResult.created[1].key = newDriveData.driveKey.toJSON();
```

2022-02-17 18:31 UTC, matibat commented on src/arfs/arfs_entities.ts
> +	// toJson(): string {}
```suggestion
```

2022-02-17 18:31 UTC, matibat commented on tests/stubs.ts
> +	return new ArFSPrivateFileMetaDataPrototype(
I guess nothing actually changed here :thinking:

2022-02-17 18:59 UTC, arielmelendez commented on src/arfs/arfs_entities.ts
>  		readonly fileId: FileID,
In retrospect, fileId should not have its own memory either. It should just be a getter that returns the entityId.

2022-02-17 19:29 UTC, matibat commented on src/arfs/arfs_entities.ts
>  		readonly fileId: FileID,
See my comment [here](https://github.com/ardriveapp/ardrive-core-js/pull/153#discussion_r809155496) about Javascript using pointers to the same instances.

2022-02-17 19:30 UTC, matibat commented on src/ardrive.ts
> +		createDriveResult.created[1].key = urlEncodeHashKey(newDriveData.driveKey.keyData);
7f6ceec8de9bd872e90ae966c4503101c7de66a7

2022-02-17 19:31 UTC, matibat commented on src/arfs/arfs_entities.ts
> +	// toJson(): string {}
265837412c0c9e9c941c9a071be9fdebaab4d906

2022-02-18 21:48 UTC, arielmelendez commented on src/types/entity_key.ts
> +	toJSON(): string {
Yea I think toString makes more sense for the implementation and for toJSON to simply call toString (see EntityID as an example).

2022-02-18 23:39 UTC, arielmelendez commented on src/ardrive.ts
> +		createDriveResult.created[0].key = newDriveData.driveKey.toJSON();
@karlprieb @fedellen @matibat I think I'd prefer the following; what do you guys this? https://github.com/ardriveapp/ardrive-core-js/pull/165

2022-02-19 20:09 UTC, matibat commented on src/ardrive.ts
> +		createDriveResult.created[0].key = newDriveData.driveKey.toJSON();
Merged down. Thanks!

2022-02-19 20:09 UTC, matibat commented on src/types/entity_key.ts
> +	toJSON(): string {
Applied: [9953305](https://github.com/ardriveapp/ardrive-core-js/pull/153/commits/995330580fcfcc95a65a785de8673c6bbf22ba37)

2022-02-19 20:10 UTC, matibat commented on src/types/entity_key.ts
> +	constructor(readonly keyData: Buffer) {}
We do assert keyData is Buffer

2022-02-19 20:18 UTC, matibat reviewed
------

2022-02-19 23:30 UTC, arielmelendez commented on src/types/entity_key.test.ts
> +		const nonBuffer: Buffer = ('non buffer type' as unknown) as Buffer;
I feel like if anyone does this, they deserve the hurt that they're going to get at runtime. I don't think we got enough utility out of the new EntityKey class to be honest. I wish we were doing more than checking that someone passed through some kind of crazy type. That itself seems superfluous in typescript world. Instead it'd be cool if we knew of a way to check for the validity of a Buffer. Wrapping the buffer for now is fine though.

2022-02-19 23:32 UTC, arielmelendez commented on src/utils/common.ts
> +		const fileKey: DriveKey = await deriveFileKey(fileToShare.fileId, driveKey);
Type here should be FileKey, not DriveKey.

2022-02-19 23:47 UTC, arielmelendez approved these changes

2022-02-22 11:04 UTC, matibat commented on src/utils/common.ts
> +		const fileKey: DriveKey = await deriveFileKey(fileToShare.fileId, driveKey);
You applied this. Thanks

2022-02-22 16:36 UTC, merged