PE-971: Makes the ArDrive methods to take a withKeys flag
ardriveapp/ardrive-core-js pull request #154
Opened 2022-02-04 12:36 UTC by matibat

Makes `ardrive.listPrivateFolder` to take an optional `withKeys` boolean to decide whether to call `arfsdao.listPrivateFolder` or `arfsdao.listPrivateFolderWithKeys`

Sub-task of PE-771

2022-02-08 02:17 UTC, fedellen commented on src/arfs/arfsdao.ts
> +	async listPrivateFolderWithKeys({
I'm surprised to see this repeating all of the `listPrivateFolder` logic. You could consider using a closure and a shared private implementaion to share the code: 

```ts
private async function someSharedListPrivateFolderFunction<T extends ArFSPrivateFileOrFolderWithPaths>(
	ArFSListPrivateFolderParams,
	entityBuilderFactory: (entity, hierarchy, driveKey) => T
): Promise<T[]>;
```

2022-02-08 02:18 UTC, fedellen commented on src/arfs/arfsdao.ts
> +	 * @returns {ArFSPrivateFileOrFolderWithPaths[]} an array representation of the children and parent folder
Update comment or remove.

2022-02-08 02:18 UTC, fedellen commented on src/arfs/arfsdao.ts
> +			(entity) => new ArFSPrivateFileOrFolderWithPathsAndKeysBuider(entity, hierarchy, driveKey)
spelling nit: `ArFSPrivateFileOrFolderWithPathsAndKeysBuider` -> `ArFSPrivateFileOrFolderWithPathsAndKeysBuilder `

2022-02-08 06:28 UTC, arielmelendez commented on src/arfs/arfsdao.ts
> +	async listPrivateFolderWithKeys({
So echoing this sentiment, my problem with this approach is that it not only duplicates logic, but it also lets values computed and stored in sensible places (i.e. ArFSPrivateFileBuilder, getPrivateFilesWithParentFolderIds, etc.) go to waste. In the current codebase, we have, or are a small step away from deriving the information we need to complete the requirements of this ticket.

I think my preferred approach might be to do something like:
- augment the constructor and membership of ArFSPrivateFile to accept and store the FileKey
- augment the constructor and membership of ArFSPrivateFileMetadataTransactionData to take and store the FileKey
- Remove keys using an Omit<> type at the locations and/or layers where necessary (e.g. ArDrive class or CLI level).

I also noticed that ArFSDao::getPrivateFile doesn't pass along the fileKey when it has the chance (it was added for caching keying purposes). This might be the case in another of other places.

2022-02-09 15:06 UTC, matibat commented on src/arfs/arfsdao.ts
> +	 * @returns {ArFSPrivateFileOrFolderWithPaths[]} an array representation of the children and parent folder
Removed. Also updated the one at `listPrivateFolder`

2022-02-10 17:45 UTC, fedellen commented on src/arfs/arfs_builders/arfs_file_builders.test.ts
> +			{ name: 'Cipher-IV', value: 'OqFPdYxI144JrO66' },
Was this resulting in a test failure in your environment?

2022-02-10 17:58 UTC, fedellen commented on src/ardrive.ts
> +	}: ListPrivateFolderParams & { withKeys?: boolean }): Promise<
Could be just added to `ListPrivateFolderParams`

2022-02-11 16:21 UTC, matibat commented on src/arfs/arfs_builders/arfs_file_builders.test.ts
> +			{ name: 'Cipher-IV', value: 'OqFPdYxI144JrO66' },
I was expecting the `fileKey` to be at the file metadataTx data, so this test broke after I wasn't able to read it from there. So I hacked into CLI and re-created the encrypted data to hold it. It is maybe wrong, I'm asking the team :nerd_face:

2022-02-11 16:38 UTC, matibat commented on src/arfs/arfs_builders/arfs_file_builders.test.ts
> +			{ name: 'Cipher-IV', value: 'OqFPdYxI144JrO66' },
Here it is the revert commit: 4917b692b3e2ee8d3c1683c90e9c3dbcdace7a35

2022-02-11 16:44 UTC, matibat commented on src/ardrive.ts
> +		});
ff380fa1fe6d5a034ae8554f816453691d994345

2022-02-11 16:48 UTC, matibat commented on src/ardrive.ts
> +	}: ListPrivateFolderParams & { withKeys?: boolean }): Promise<
There: 0dfbba8719fb55d97e00c2489052d151da397e1e

2022-02-11 16:58 UTC, fedellen commented on src/arfs/arfsdao.ts
>  	 * @returns {ArFSPrivateFileOrFolderWithPaths[]} an array representation of the children and parent folder
Does `ArFSPrivateFileOrFolderWithPaths` exist anymore here?

2022-02-11 17:41 UTC, matibat commented on src/arfs/arfsdao.ts
>  	 * @returns {ArFSPrivateFileOrFolderWithPaths[]} an array representation of the children and parent folder
It doesn't! :o

2022-02-11 17:49 UTC, arielmelendez commented on src/ardrive.ts
> +	public async getPrivateFileKeyless({
Is it really necessary for the DAO to provide this utility when all that needs to be done to get a keyless instance is to wrap an ArFSPrivateFile with the keyless constructor? Just not sure this API has a lot of utility as written. For example, what are its behaviors other than using a known constructor (which exactly matches the return type here)?

2022-02-11 18:07 UTC, matibat commented on src/ardrive.ts
> +	public async getPrivateFileKeyless({
This method was required to avoid the `file-info` CMD changing its behavior after exposing the `fileKey` on the `ArFSPrivateFile` class.
And I've put the method at the `ArDrive` class in order for the CLI layer to do not map the file to its key-less version.

Does it make sense?

2022-02-11 18:11 UTC, matibat commented on src/arfs/arfsdao.ts
>  	 * @returns {ArFSPrivateFileOrFolderWithPaths[]} an array representation of the children and parent folder
Updated the docblock: 920b96590f9abdf2e73b8452e36d9abe512aa790

2022-02-12 00:37 UTC, matibat reviewed
****

2022-02-14 21:54 UTC, fedellen commented on src/ardrive.ts
> +	public async getPrivateFileKeyless({
If the current iterations of the `getPrivateFile` and `getPrivateFolder` ArDrive methods have now been changed to include `fileKey` and/or `driveKey` then to remain backwards compatible they need to be adjusted here.

I'd say you could just extend your `withKeys = false` boolean parameter to be applied to the existing private `file-info` and `folder-info` methods and handle that condition rather than defining new API

2022-02-16 14:11 UTC, matibat commented on src/ardrive.ts
> +	public async getPrivateFileKeyless({
There will be a big TODO for this. I created [a task](https://ardrive.atlassian.net/browse/PE-1027) to avoid making this one last longer.

2022-02-16 14:39 UTC, fedellen commented on src/ardrive.ts
> +	public async getPrivateFileKeyless({
Doesn't seem like this one can be a TODO. We're breaking backwards compatibility here by leaking `fileKey` to anyone using `ardrive.getPrivateFile`

2022-02-18 17:01 UTC, matibat commented on src/ardrive.ts
> +	public async getPrivateFileKeyless({
`ArDrive.getPrivateFile` returns the keyless version now, unless you specify `withKeys = true`
ce4b422c959f0a4f61f8cc46fc2a6635e788a4b0

2022-02-22 03:29 UTC, arielmelendez requested changes
There's a backwards ternary and a parameter that makes no sense in the public context. Why didn't either of those things cause test failures?

2022-02-22 03:29 UTC, arielmelendez commented on src/ardrive.ts
> +		return withKeys ? new ArFSPrivateFileKeyless(file) : file;
This ternary is backwards.

2022-02-22 03:29 UTC, arielmelendez commented on src/arfs/folder_hiararchy.test.ts
> +describe('FolderHierarchy class', () => {
I don't like this pattern of creating test files with unimplemented tests. This creates mental overhead for reviewers and in this specific case distracts from the core purpose of the PR.

2022-02-22 03:29 UTC, arielmelendez commented on src/types/ardrive_types.ts
> +	withKeys?: boolean;
Why would this be in the Public file params? Public files have no keys.

2022-02-22 10:30 UTC, matibat commented on src/arfs/folder_hiararchy.test.ts
> +describe('FolderHierarchy class', () => {
At the previous Retro we emphasized the importance of code changes & tests to share the same PR. :+1:

2022-02-22 10:31 UTC, matibat commented on src/types/ardrive_types.ts
> +	withKeys?: boolean;
It was because the private version extends it. Applied only to the private version: [802afb9](https://github.com/ardriveapp/ardrive-core-js/pull/154/commits/802afb95c910d2abd91e50b1136da9f1de661265)

2022-02-22 14:08 UTC, karlprieb commented on src/arfs/folder_hiararchy.test.ts
> +describe('FolderHierarchy class', () => {
Yes, we discussed that, but we should implement the tests not add boilerplate ;)

2022-02-22 14:10 UTC, karlprieb approved these changes

2022-02-22 16:38 UTC, merged