PE-981: implements unit tests for FolderHierarchy
ardriveapp/ardrive-core-js pull request #156
Opened 2022-02-04 19:16 UTC by matibat

2022-02-09 21:51 UTC, arielmelendez commented on src/arfs/folder_hiararchy.test.ts
> +	it('rootNode attribute always return a FolderTreeNode', () => {
Nit: return -> returns

2022-02-09 21:53 UTC, arielmelendez commented on src/arfs/folder_hiararchy.test.ts
> +import { expect } from 'chai';
The file name for this file is misspelled. `hiararchy` -> `hierarchy`

2022-02-09 21:53 UTC, arielmelendez requested changes
Fix file name

2022-02-09 21:56 UTC, arielmelendez commented on src/arfs/folder_hiararchy.test.ts
> +		expect(treeRoot).to.be.instanceOf(FolderTreeNode);
What is the utility of all the type checks in these tests? Why is type the foremost important concept? And why are we not just relying on TypeScript to tell us the types are what we expect?

2022-02-09 22:04 UTC, arielmelendez commented on src/arfs/folder_hiararchy.test.ts
> +		stubHierarchy = FolderHierarchy.newFromEntities(allFolders);
It's not great from a reader's standpoint that this is called a "stub". It's actually the object under test. What's stubbed are the folders themselves. Consider naming it `folderHierarchy`.

2022-02-09 22:12 UTC, arielmelendez commented on src/arfs/folder_hiararchy.test.ts
> +	const stubRootFolder = stubPublicFolder({
It's a bit annoying that the `stubPublicFolder` function doesn't actually set the folderId that's passed it. It assigns it to the entityId (which is fine given the way that silly ArFSFileOrFolderEntity class is architected) but needs to also follow up after construction and set the folderID. Better yet `ArFSFileOrFolderEntity` should be changed to an abstract class, and the folderId field should be an abstract property that returns the entity ID as null for files and as the entity ID for folders.

2022-02-09 22:57 UTC, arielmelendez commented on src/arfs/folder_hiararchy.test.ts
> +		const subTree = stubHierarchy.subTreeOf(stubEntityIDParent);
In what sense is this actually evaluating "correctness"?

2022-02-09 23:02 UTC, arielmelendez commented on src/arfs/folder_hiararchy.test.ts
> +		expect(allFolderIDsWithoutRoot).to.have.deep.members(stubFolderIDsWithoutRoot);
You should check counts as well since the list in which members are sought might have more items than the output of allFolderIds.

2022-02-09 23:03 UTC, arielmelendez commented on src/arfs/folder_hiararchy.test.ts
> +		expect(nodes).to.include(rootNode);
Why not check that all the nodes are included?

2022-02-09 23:05 UTC, arielmelendez commented on src/arfs/folder_hiararchy.test.ts
> +		const folderIDs = stubHierarchy.folderIdSubtreeFromFolderId(rootNode.folderId, Number.MAX_SAFE_INTEGER);
Looks like we're missing tests that actually exercise the depth limitations.

2022-02-10 16:56 UTC, matibat commented on src/arfs/folder_hiararchy.test.ts
> +		stubHierarchy = FolderHierarchy.newFromEntities(allFolders);
Applied: a340cbe1ac70309e7ce9db4bf52a59c3688c004e

2022-02-10 17:01 UTC, matibat commented on src/arfs/folder_hiararchy.test.ts
> +		const subTree = stubHierarchy.subTreeOf(stubEntityIDParent);
Nice question! Currently, it is only ensuring the returned types are instances of the correct classes. No more than that for now... I might check against the node's property values to assert the correct `folderId` is returned :thinking:

2022-02-10 17:05 UTC, matibat commented on src/arfs/folder_hiararchy.test.ts
> +		expect(nodes).to.include(rootNode);
I don't have access to all nodes. Unless I manually instantiate 'em and use the `FolderHierarchy`'s constructor instead of its `newFromEntitires` method.

2022-02-10 17:06 UTC, matibat commented on src/arfs/folder_hiararchy.test.ts
> +		const folderIDs = stubHierarchy.folderIdSubtreeFromFolderId(rootNode.folderId, Number.MAX_SAFE_INTEGER);
You are right! Nice catch :sweat_smile:

2022-02-10 17:32 UTC, matibat commented on src/arfs/folder_hiararchy.test.ts
> +	const stubRootFolder = stubPublicFolder({
Applied: 9ff670a0d3b008918c2f7194e79a2017ba133957

2022-02-10 19:15 UTC, matibat commented on src/arfs/folder_hiararchy.test.ts
> +		expect(allFolderIDsWithoutRoot).to.have.deep.members(stubFolderIDsWithoutRoot);
Applied: ff2fbe4389009178261ee88f4e518463245f119c

2022-02-15 20:31 UTC, matibat commented on src/arfs/folder_hiararchy.test.ts
> +		const folderIDs = stubHierarchy.folderIdSubtreeFromFolderId(rootNode.folderId, Number.MAX_SAFE_INTEGER);
[3050db5](https://github.com/ardriveapp/ardrive-core-js/pull/156/commits/3050db5df584751d25c9c379914f09a04b350b48)

2022-02-22 05:31 UTC, arielmelendez commented on src/arfs/folder_hierarchy.test.ts
> +			it('the sub-tree of maxDepht zero has only one node on it', () => {
maxDepht -> maxDepth

2022-02-22 05:32 UTC, arielmelendez commented on src/arfs/folder_hierarchy.test.ts
> +			it('the sub-tree of maxDepht zero has only one node on it', () => {
This test is failing for me locally.

2022-02-22 10:35 UTC, matibat commented on src/arfs/folder_hierarchy.test.ts
> +			it('the sub-tree of maxDepht zero has only one node on it', () => {
Yes! `FolderHierarchy` has two bugs.
 - One es fixed at this PR (bb028db3295aea2affefde6a2fbc6537da82832f)
 - and the other is a known defect [PE-1012](https://ardrive.atlassian.net/browse/PE-1012)

2022-02-22 10:37 UTC, matibat commented on src/arfs/folder_hierarchy.test.ts
> +			it('the sub-tree of maxDepht zero has only one node on it', () => {
Ty: 78dc7b808a28892612c64c99244757efd3ae2f4c

2022-02-22 16:24 UTC, matibat commented on src/arfs/folder_hierarchy.test.ts
> +			it('the sub-tree of maxDepht zero has only one node on it', () => {
I'll skip that test and leave there a comment indicating the reason (PE-1012)

2022-02-22 16:34 UTC, matibat commented on src/arfs/folder_hierarchy.test.ts
> +			it('the sub-tree of maxDepht zero has only one node on it', () => {
1b21f2bc6c116d1fd9e289fbea3eb8f6d78ece0f

2022-02-22 18:35 UTC, karlprieb approved these changes

2022-02-22 21:21 UTC, arielmelendez commented on src/arfs/folder_hierarchy.test.ts
> +			it('maxDepth of zero', () => {
These test names are not to the standards we expect. As written, this test name would be:

`FolderHierarchy class FolderTreeNode class the maxDepth parameter maxDepth of zero`

This test name does not:
- explain very clearly which class is under test
- explain very clearly which function of that class is under test
- explain very clearly what the inputs and/or conditions of the test are
- explain very clearly what the behaviors and outputs of the object/function under test are as a result.

When a test lacks one or more of the above, it's very difficult for a reader to assess whether the appropriate test coverage is being applied.

When I look at the body of this test, what I see being tested is:
- 'FolderHierarchy::nodeAndChildrenOf' being tested with some FolderTreeNode and a max depth of 0 (note: it's possible that this function could be used with a FolderTreeNode that's not even in the hierarchy. That points to questionable class design. Maybe this should be a static FolderTreeNode function instead since no private state of either FolderHierarchy or FolderTreeNode is used?) and making sure that the returned list is of the right length, but NOT checking whether it's made of the right nodes (this is a shortcoming).
- 'FolderHierarchy:: folderIdSubtreeFromFolderId' is being tested with a known good folderId (by the way, that function will probably crash if a bad folderId is passed... maybe not the best type and/or function design...) and a max depth of 0. Again, it tests that it the returned list is of the right length, but does NOT check whether it's made of the right nodes (this is, again, a shortcoming).

So in summary:
- The test name is not indicative of what's actually being tested
- Two functions (i.e. UNITS) are under test instead of one
- The inputs aren't clearly/fully articulated in the test name
- The expected outputs are not articulated at all in the test name
- The outputs are only partially verified.

2022-02-22 21:33 UTC, arielmelendez approved these changes
These tests are not everything that we'd want, but are better than what we had (which was nothing). Given the time invested thus far I think it's time for us to move on.

2022-02-23 00:42 UTC, merged