PE-1086: Progress callback on tx uploader
ardriveapp/ardrive-core-js pull request #180
Opened 2022-03-08 17:01 UTC by fedellen

This PR adds a debounced progress callback to the concurrent tx uploader which can currently be enabled with an ENV variable, similar to the persistent cache pattern

2022-03-08 18:57 UTC, fedellen commented
Notably, this minimalistic approach doesn't account for multiple transactions coming in from `uploadAllEntities` and only reports progress on one transaction at a time.

Will need to modify the overlying method to include that info

2022-03-08 21:34 UTC, arielmelendez commented on src/arfs/arfsdao.ts
> +								if (!debounce) {
Minor UX improvement might be to allow the 100% message to always come through.

2022-03-08 21:35 UTC, arielmelendez commented on src/arfs/arfsdao.ts
> +		let debounce = false;
nit: only relevant if !dryRun. Might be better to improve locality of reference by moving in that if block.

2022-03-08 21:36 UTC, arielmelendez commented on src/arfs/arfsdao.ts
> +					console.info('Transaction upload complete!');
Could be nice to have the txId in here.

2022-03-08 21:37 UTC, arielmelendez commented on src/arfs/arfsdao.ts
> +									console.info(`Transaction Upload Progress: ${pct}%`);
Could be nice to have the txId in here.

2022-03-08 21:38 UTC, arielmelendez commented on src/arfs/multi_chunk_tx_uploader.ts
> +		if (progressCallback) {
Is this check necessary?

2022-03-08 21:40 UTC, arielmelendez commented on src/arfs/multi_chunk_tx_uploader.ts
> +			if (this.progressCallback) {
You can use optional chaining on functions:
```
this.progressCallback?.(this.pctComplete);
```

2022-03-08 21:40 UTC, arielmelendez requested changes
A few minor comments.

2022-03-09 02:00 UTC, arielmelendez approved these changes

2022-03-09 14:18 UTC, merged