chore(deps): bump node, yarn, eslint, typescript, versions PE-1252
ardriveapp/ardrive-core-js pull request #219
Opened 2023-08-01 21:58 UTC by fedellen

2023-08-03 17:44 UTC, fedellen commented on src/utils/gateway_api.ts
> +			this.lastError = err instanceof Error ? err.message : ((err as unknown) as string);
2d269e3

2023-08-03 17:59 UTC, dtfiedler submitted a review, later dismissed

2023-08-03 18:38 UTC, arielmelendez commented on package.json
> +		"@types/node": "^20.4.5",
Is this the right types version for node 18?

2023-08-03 18:41 UTC, arielmelendez commented on src/utils/gateway_api.ts
> +			this.lastError = err instanceof Error ? err.message : (err as string);
Perhaps better to toString or interpolate this?

2023-08-03 18:44 UTC, arielmelendez requested changes
Left some minor suggestions. However, I believe we need some README updates as a result of these changes.

2023-08-04 15:35 UTC, fedellen commented on package.json
> +		"@types/node": "^20.4.5",
4a32b4f

2023-08-04 15:36 UTC, fedellen commented on src/utils/gateway_api.ts
> +			this.lastError = err instanceof Error ? err.message : (err as string);
e8261ef

2023-08-04 16:17 UTC, arielmelendez approved these changes

2023-08-09 19:05 UTC, fedellen commented on package.json
> +		"node": ">=18.17.0"
Any thoughts on limiting our users of Core to node 18.17.0?

2023-08-10 15:39 UTC, merged