PE-3: Setup supporting testing libraries
ardriveapp/ardrive-core-js pull request #56
Opened 2021-06-22 20:27 UTC by fedellen

This PR sets up Sinon for mocking, Istanbul for code coverage, and power-assert as a powerful debugging tool. It also adds the configuration files necessary to get up and running with each library.

I wrote an `example.test.ts` file to show and test the functionality of each library. This file is also a placeholder for where the integration tests would eventually be. I wanted to make sure we could test files in that directory with this setup.

The process of using the testing environment is documented in the `README` for now.

2021-06-22 21:19 UTC, arielmelendez requested changes
yarn cache files should not be in this pull request. They'll blow up our repo :)

https://yarnpkg.com/getting-started/qa#which-files-should-be-gitignored

2021-06-22 21:28 UTC, arielmelendez requested changes
Please update the README with instructions for testing the codebase.

2021-06-23 01:53 UTC, fedellen commented
> yarn cache files should not be in this pull request. They'll blow up our repo :)
> 
> https://yarnpkg.com/getting-started/qa#which-files-should-be-gitignored

I almost asked about this one when they started showing up in my commits, but I did go to that exact link which is referenced in our `.gitignore` file. We have the same setup they recommend with "Zero-Installs":

https://github.com/ardriveapp/ardrive-core-js/blob/28403296465f1ba48affb336a60f4b5f1f2d37f3/.gitignore#L41-L50

If we're not using the Zero-Installs I can safely change that up.

> Please update the README with instructions for testing the codebase.

Sounds good! I'll add some more testing instructions to the README.md

2021-06-23 13:29 UTC, arielmelendez commented
> If we're not using the Zero-Installs I can safely change that up.
My understanding is that the team doesn't use zero-installs day-to-day. We only use it when accepting external PRs (which rarely happen if I'm not mistaken).

In thinking about external PRs, I'm not sure if that means we HAVE to use zero-installs all the time or not, specifically when we think about the impact on our CI system (i.e. CI would run for the PR and we'd have to think about potential impacts of the build container ingesting the potential hazardous external lib).

@agsuy , any insights?

2021-06-23 14:22 UTC, agsuy commented
> > If we're not using the Zero-Installs I can safely change that up.
> 
> My understanding is that the team doesn't use zero-installs day-to-day. We only use it when accepting external PRs (which rarely happen if I'm not mistaken).
> 
> In thinking about external PRs, I'm not sure if that means we HAVE to use zero-installs all the time or not, specifically when we think about the impact on our CI system (i.e. CI would run for the PR and we'd have to think about potential impacts of the build container ingesting the potential hazardous external lib).
> 
> @agsuy , any insights?

The main drive of using Yarn2 IS Zero Installs (use repo as soon as you clone it) so we all resolve the same packages across all envs and there is not local regeneration (yarn install) lowering overall entropy. https://yarnpkg.com/features/zero-installs

2021-06-23 17:53 UTC, matibat approved these changes
Seems good!

2021-06-23 20:08 UTC, arielmelendez commented on README.md
> +## Testing the Library
Might make sense to move this above the VS Code integration section.

2021-06-23 20:09 UTC, arielmelendez commented on README.md
> +This library is setup for [Mocha] testing with [Chai] and [Sinon].
Did you intend to add some URL links here for Mocha, Chai, and Sinon?

2021-06-23 20:10 UTC, arielmelendez commented on README.md
> +yarn test -g 'my specific unit test'
Can you give some more descriptive examples here? E.g. specific test names, specific test classes/files, specific folders?

2021-06-23 20:15 UTC, arielmelendez commented on README.md
> +This library is setup for [Mocha] testing with [Chai] and [Sinon].
Same for other links below.

2021-06-23 20:15 UTC, arielmelendez commented on README.md
> +[Istanbul.js (nyc)][nyc] has been added for code coverage. On each `yarn test`, nyc will output a summary in the terminal. In addition, a more detailed HTML version will output to the `/coverage` dir
nit: `for code coverage reporting`.

2021-06-23 20:18 UTC, arielmelendez commented on README.md
> +There are many different syntax options available with the Chai library, which can be found in their [documentation][chai-doc]. Here is an example unit test for a basic input/output function using Mo
Rather than putting code examples here, it might be best to put them in actual source files in the correct folders. To that point, let's be instructive here about where test files should live. I believe the pattern we're looking to use is to colocate unit test files next to their analogous source files and to put integration (and maybe end-to-end?) test files in analogous folder structures under the ./tests folder.

2021-06-23 20:19 UTC, arielmelendez commented on README.md
> +There are many different syntax options available with the Chai library, which can be found in their [documentation][chai-doc]. Here is an example unit test for a basic input/output function using Mo
When we create the example test files, it might be good for us to advise best practices around test setup and naming conventions (e.g. I like that you've used terms like input, expectedOutput, etc.)

2021-06-23 20:20 UTC, arielmelendez commented on README.md
> +To leverage the Sinon library, simply import the methods you need into your test file:
All of this could live in the example test files.

2021-06-23 20:21 UTC, arielmelendez commented on README.md
> +Then use `assert` in your error throwing test case:
May want to note that you'd be REPLACING (commenting out) your existing failing assert and replacing with power assert syntax.

2021-06-23 20:21 UTC, arielmelendez commented on README.md
> +[mocha]: https://github.com/mochajs/mocha
Consider a sub-heading for these links

2021-06-23 20:23 UTC, arielmelendez commented on README.md
> +This library is setup for [Mocha] testing with [Chai] and [Sinon].
We might also want to point out where the configuration files live.

2021-06-23 20:25 UTC, arielmelendez requested changes
See my comments. Nice work so far! Thanks.

2021-06-23 20:29 UTC, fedellen commented on README.md
> +This library is setup for [Mocha] testing with [Chai] and [Sinon].
The links are working on my end. This is a little markdown trick, they attach to the link variables listed below.

This is just a style habit I've picked up for re-usability, I can move the links into the content.

2021-06-23 20:35 UTC, fedellen commented on README.md
> +[mocha]: https://github.com/mochajs/mocha
These are hidden when viewing the produced markdown file. They are the link variables I mentioned above, only viewable in the raw file. I will relocate them all into the content

2021-06-23 20:50 UTC, arielmelendez commented on README.md
> +This library is setup for [Mocha] testing with [Chai] and [Sinon].
> This is just a style habit I've picked up for re-usability, I can move the links into the content.

No need. I just wasn't aware of that markdown feature. Thanks for the heads up!

2021-06-23 21:38 UTC, fedellen commented on README.md
> +There are many different syntax options available with the Chai library, which can be found in their [documentation][chai-doc]. Here is an example unit test for a basic input/output function using Mo
I do have an `example.test.ts` file set up in the /test directory (I can change that to /tests). These examples are mostly based on the code in that file. That example was meant to be instructive, to test that the libraries were functional with our codebase, and to make sure our test command would reach that directory.

I will be expanding that example file to include the information I added to the README. And I'll clean up that file to use some better practices. Its actually a unit test that has been split up into various examples, and doesn't really belong in the integration test directory. I just needed some test in that directory to prove it was working.

I'll also add a section in the README on where each type of tests should live. I think everyone is in agreement with you on where to locate tests.

2021-06-25 20:44 UTC, agsuy commented on README.md
> +[mocha]: https://github.com/mochajs/mocha
I think it would be easier to edit the file in the future if we keep all the links at the end rather than with the traditional [name](link) format. We just need to make sure we do that for all the links tho.

2021-06-29 05:23 UTC, arielmelendez commented on README.md
> +Sinon can be used to create spies, mocks, fakes, stubs, and more. There are some basic examples of using the library shown files shared above.
Nit: "shown files" -> "in the shown files" or similar

2021-06-29 05:24 UTC, arielmelendez commented on README.md
> +## Testing the Library
This whole section is amazing.

2021-06-29 15:21 UTC, agsuy commented
You might want to add to yarn clean any cache/files generated by test suites.

2021-06-29 16:25 UTC, arielmelendez approved these changes

2021-06-29 16:34 UTC, merged