PE-50: Fix Duplicate ArDrive Fee
ardriveapp/ardrive-core-js pull request #59
Opened 2021-07-09 17:14 UTC by fedellen

This PR fixes #57  on the `dev` branch

`uploadArFSFileData` does not need to handle the fee in this case, because `uploadArDriveFiles` handles fees for all files at the end of an upload batch. Handling the fee per individual file is unnecessary here.

I self tested this with some awkward results, but with this hotfix the cost is always LESS than expected now rather than MORE. All .png uploads tested were around 300 bytes. The Cost was how much AR was taken from the active wallet when the transactions had been settled. The expected result was taken from the CLI's estimation upon confirming (y/n):

## Before hotfix 

- heart.png
  - Cost: 0.000026889017 AR 
  - Expected: 0.000012319000000000002 
  - Difference: 0.000014570017 AR **MORE** than expected
  
- coin.png
  - Cost: 0.000026825254 AR
  - Expected: 0.000012255 AR
  - Difference: 0.000014570254 AR **MORE** than expected

## After hotfix 

- key.png
  - Cost: 0.000003503865 AR 
  - Expected: 0.000012263000000000001 
  - Difference: 0.000008759135 AR **LESS** than expected
  
- barrel.png
  - Cost: 0.000003566591AR
  - Expected: 0.000012324000000000001 AR
  - Difference: 0.000008757409 AR **LESS** than expected

2021-07-10 22:41 UTC, agsuy commented
How are you calculating the expected fee?

2021-07-10 22:44 UTC, fedellen commented
> How are you calculating the expected fee?

Its the estimation from the cli as you confirm upload. I'm going to be digging into where and how that is calculated. But the AR is deducted when the transaction is settled, so there is a natural delay between estimation and payment.

2021-07-12 14:45 UTC, agsuy commented
> > How are you calculating the expected fee?
> 
> Its the estimation from the cli as you confirm upload. I'm going to be digging into where and how that is calculated. But the AR is deducted when the transaction is settled, so there is a natural delay between estimation and payment.

1. So is this a defect on the way we calculate fees at CLI level that we want to report as a defect?
2. Its worth using CLI calculations as reference if we know they are wrong?

2021-07-12 15:46 UTC, fedellen commented
> 1. So is this a defect on the way we calculate fees at CLI level that we want to report as a defect?
> 2. Its worth using CLI calculations as reference if we know they are wrong?

1. After digging further I learned that there is another defect in the way we are estimating fees here. The method is calculating 1003210 bytes in a MB, when there are actually 1048576 bytes in a MB:

```ts
// From function `getPriceOfNextUploadBatch` in `node.ts` 

// Get all files that are ready to be uploaded
const filesToUpload: types.ArFSFileMetaData[] = getDb.getFilesToUploadFromSyncTable(login);
if (Object.keys(filesToUpload).length > 0) {
  // Estimate the size by getting the size of 1MB
  const priceFor1MB = await getWinston(1000000);
  const pricePerByte = priceFor1MB / 1003210; // <-- There are actually 1048576 bytes in a MB
```

The method also makes an assumption for the metadata price (in multiple places) which could be effecting it's accuracy:

```ts
totalArweaveMetadataPrice += 0.0000005; // Ths is the price we assume it costs for a metadata tx
```

2. I believe if we fix the defect above the estimation will be more accurate. However, the estimation will always have this natural delay and should still be slightly inaccurate, especially when uploading a LOT of large files. 

Having an estimation is way more user friendly than not having an estimation, but I think we should at least warn the user that its just an estimation and AR price is volatile and "could" shift within the 2-15 minutes that an upload can take to settle.

Also, I found that during an upload there is an additional estimation that is shown to the user in method `uploadArFSFileData` of `arfs.ts`. I haven't been using this one in my expected results because there is no prompt to confirm the upload at the time it is shown. But, this estimation does not include the ArDrive community fee -- so it is underestimating the cost as well.

I'll ready a couple commits to clear things up here

2021-07-12 22:08 UTC, arielmelendez commented
> This PR fixes #57 on the `dev` branch
> 
> `uploadArFSFileData` does not need to handle the fee in this case, because `uploadArDriveFiles` handles fees for all files at the end of an upload batch. Handling the fee per individual file is unnecessary here.
> 
> I self tested this with some awkward results, but with this hotfix the cost is always LESS than expected now rather than MORE. All .png uploads tested were around 300 bytes. The Cost was how much AR was taken from the active wallet when the transactions had been settled. The expected result was taken from the CLI's estimation upon confirming (y/n):
> 
> ## Before hotfix
> * heart.png
>   
>   * Cost: 0.000026889017 AR
>   * Expected: 0.000012319000000000002
>   * Difference: 0.000014570017 AR **MORE** than expected
> * coin.png
>   
>   * Cost: 0.000026825254 AR
>   * Expected: 0.000012255 AR
>   * Difference: 0.000014570254 AR **MORE** than expected
> 
> ## After hotfix
> * key.png
>   
>   * Cost: 0.000003503865 AR
>   * Expected: 0.000012263000000000001
>   * Difference: 0.000008759135 AR **LESS** than expected
> * barrel.png
>   
>   * Cost: 0.000003566591AR
>   * Expected: 0.000012324000000000001 AR
>   * Difference: 0.000008757409 AR **LESS** than expected

When expressing really small AR values, it can be helpful to express them in Winston with commas in the usual places to help the eye pick up magnitudes more quickly. e.g. for your first example:
heart.png
Cost: 26,889,017 Winston
Expected: 12,319,000 Winston
Difference: 14,570,017 Winston **MORE** than expected (~2.18x)

2021-07-12 22:35 UTC, arielmelendez commented on src/common.ts
> +export function winstonToAr(winston: number): number {
We should throw an exception if the absolute value of the Winston number is less than 1.0 since there's no such thing as fractional Winston; it's the smallest unit of AR.

2021-07-12 22:35 UTC, agsuy commented on src/common.ts
> +export function winstonToAr(winston: number): number {
For reference: https://docs.arweave.org/developers/server/http-api#ar-and-winston

2021-07-12 22:36 UTC, arielmelendez commented on src/node.ts
> +		// Add the ArDrive community fee
👍

2021-07-12 22:44 UTC, arielmelendez commented on src/constants.ts
> +export const minimumArDriveARFee = 0.00001; // AR
Could be nice to include a link here to the provenance of this value (i.e. the Community Improvement Proposal Doc https://arweave.net/Yop13NrLwqlm36P_FDCdMaTBwSlj0sdNGAC4FqfRUgo that was voted upon recently  - vote #82 at https://community.xyz/#-8A6RexFkpfWwuyVO98wzSFZh0d6VJuI-buTJvlwOJQ/votes/)

2021-07-12 23:16 UTC, arielmelendez commented on src/constants.ts
> +export const minimumArDriveARFee = 0.00001; // AR
Nit: "Tip" is the common word that's used.

2021-07-13 00:11 UTC, arielmelendez commented on src/smartweave.ts
> +		return 15; // Default fee of 15% if we cannot pull it from the community contract
This is another magic number worth factoring out as it's used here and on line 15 above. Additionally, the function name should be updated to include the UNIT of the returned value. In this case it's a percentage. And this function's value is that it is getting the fee from the contract, so we may further want to include that so that we can disambiguate it from a function that returns the fee in Winston when provided a data size in bytes.

2021-07-13 00:14 UTC, arielmelendez commented on src/public/arfs.ts
>  		arPrice = +winston * 0.000000000001;
Let's factor that multiplier out and have a constant like `arPerWinston`.

2021-07-13 00:33 UTC, arielmelendez commented on src/public/arfs.ts
> +		const arDriveFee = arPrice * ((await getArDriveFee()) / 100);
It might be best to return a decimal fraction value from whatever getArDriveFee is going to be renamed to in order to prevent callers from having to remember to divide by 100.

2021-07-13 00:36 UTC, arielmelendez commented on src/node.ts
>  		let arDriveFee = +totalArweaveDataPrice.toFixed(9) * ((await getArDriveFee()) / 100);
We get 12 digits of AR precision when working with Winstons. Why is this `toFixed(9)`?

2021-07-13 00:42 UTC, arielmelendez commented on src/common.test.ts
> +describe('The winstonToAr function', () => {
Test cases to consider:
1. Negative values (OK)
2. ANY non-integer value of Winston is an exception
3. 0 (zero is valid)
4. 1 AR = 1,000,000,000,000 Winston
5. 0.999999999999 = 999,999,999,999 Winston

2021-07-13 00:42 UTC, arielmelendez requested changes
See my comments, requests, and questions. Thanks!

2021-07-13 02:22 UTC, fedellen commented on src/common.ts
> +export function winstonToAr(winston: number): number {
Is it worth it here to throw an exception for this case or should we simply round the number to the nearest integer before attempting conversion? 

Having it round for us would give the function a little more utility and become easier to use outside of a try/catch block. Ideally, the Arweave gateway will only ever return us a whole winston number. So the only way we normally would end up with a decimal is from some type of conversion we made in the code after we have obtained that value from the gateway.

A decimal of a winston is such a small fraction I'm just not sure its "worth" throwing errors.

So @arielmelendez , do you think this function should be:

```ts
// With exception
export function winstonToAr(winston: number): number {
  if (Number.isInteger(winston)) throw new Error(`Winston value not an integer: ${winston}`);
  return winston * 0.000000000001;
}
```

Or:

```ts
// With rounding
export function winstonToAr(winston: number): number {
  return Math.round(winston) * 0.000000000001;
}
```

2021-07-13 18:09 UTC, fedellen commented on src/node.ts
>  		let arDriveFee = +totalArweaveDataPrice.toFixed(9) * ((await getArDriveFee()) / 100);
Thats a good question. I'll ask Phil if there were any technical limitations behind the decision of using 9 digits

2021-07-13 22:18 UTC, arielmelendez commented on src/common.test.ts
> +/**
This docblock seems redundant and brittle (tests might be added/changed/removed and you'd have to come update again here) since the tests are self describing.

2021-07-13 22:24 UTC, arielmelendez commented on src/common.test.ts
> +		expect(winstonToAr(62_345_548_231)).to.equal(0.062_345_548_231);
Ooooh numeric separators. Sexy. Can't say I've ever seen that in the wild, but I'm into it :D

2021-07-13 22:27 UTC, arielmelendez commented on src/common.ts
> +export function winstonToAr(winston: number): number {
Yea we'll see how this goes. Thanks for the update.

2021-07-13 22:31 UTC, arielmelendez commented on src/public/arweave.ts
> +		if (tip < minimumArDriveCommunityTip) {
```
tip = Math.max(tip, minimumArDriveCommunityTip);
```
might be a bit more concise.

2021-07-13 22:35 UTC, arielmelendez commented on src/public/arfs.ts
>  		arPrice = +winston * 0.000000000001;
Bump

2021-07-13 22:36 UTC, arielmelendez requested changes
Just one more constant to factor out. And please follow up on the toFixed(9) issue.

2021-07-14 17:48 UTC, arielmelendez commented on .mocharc.js
> +	timeout: '10000', // 10 seconds for smartweave contract reading
Is there no way to change this value on the fly when we need to rather than extending the timeouts across the app? (I might be misinterpreting the usage of this constant)

2021-07-14 17:48 UTC, arielmelendez commented on src/common.test.ts
> +// winstonToAr multiplies by 0.000000000001
I think even this small comment is redundant 😬

2021-07-14 18:01 UTC, arielmelendez commented on src/common.ts
> +	if (!Number.isInteger(winston)) throw new Error(`Winston value not an integer: ${winston}`);
A thought.... isInteger gives us 64 bits of precision to work with. E.g.
```
Number.isInteger(5.000000000000001); // false
Number.isInteger(5.0000000000000001); // true
```
All that means is that tiny fractional amounts of Winston might get treated as integers but ALSO large amounts of Winston with some large fractional amount might also be considered an integer. That's probably ok.

2021-07-14 19:34 UTC, fedellen commented on src/common.ts
> +	if (!Number.isInteger(winston)) throw new Error(`Winston value not an integer: ${winston}`);
Thats interesting. Do you know any good workaround for this?

I just tried using `winston % 1 !== 0` and also `winston.toString().indexOf('.') !== -1` but both are similarly failing for the above test case.

JavaScript seems to be saying exactly `5.0000000000000001 === 5`. And it seems to also round up if that last digit is meant to: `5.000_000_000_000_000_5 === 5.000_000_000_000_001`

2021-07-14 19:39 UTC, fedellen commented on .mocharc.js
> +	timeout: '10000', // 10 seconds for smartweave contract reading
I did find a way to change it on the fly and updated it.

We can directly change settings for a mocha test in the describe block:

```ts
describe('The estimateArCost function', function () {
  // Set timeout to 10 seconds for smartweave contract reading
  this.timeout(10000);
  
  // ...

```

2021-07-14 20:24 UTC, fedellen commented
This all should have been a different branch with a new JIRA ticket (I'll watch my scope creep next time, just started digging around) -- but in this branch I recently made two significant changes to the community tip fetching and the estimation process.

## Community Tip

`getArDriveFee` is now `getArDriveTipPercentage` and will grab tip percentage from the community vote at it's block height of `578358`. This alone reduces the time to read the contract from 40000ms-60000ms to 4000ms-6000ms. In addition it will save this value for that session, causing synchronous retrieval on subsequent calls.

If the fee has not been fetched from the exact setting (the 40-60 second contract read), it will also start a background task to go fetch that setting. This task will update the value retrieved above when it finishes. 

The way I set up this background task is the first time I've tried "not awaiting" code like this. I've done a good amount of self testing with the Core -> CLI pipeline and I'm not running into any problems as of yet. But I'm not overly confident about this background task because I haven't used this pattern before. The [code is located](https://github.com/ardriveapp/ardrive-core-js/pull/59/files#diff-7015ad9d4d41d585b726513fb0bfbe45a9916e1c18c321721daf6e2aecd5aabe) in `smartweave.ts` 

## Estimation

The estimation process has been heavily refactored and slightly adjusted. I factored out two functions that have been shared into other places of the code: `estimateArCost` and `getArDriveCommunityTip`. In doing this I simplified and documented some of the logic inside the main price estimation function: `getPriceOfNextUploadBatch`.

One change to note here is that I have increased the `assumedMetadataTxPrice` from `0.000_000_500_000` to `0.000_002_500_000`.  I found that the meta data estimations have been far too low while working with tiny files.

### Latest estimations in Winston

Overall the estimations have become a lot more accurate, and generally estimate slightly more than the actual value taken.

- lilesplode.png (263 bytes)
  - estim : 15,363,052 
  - actual: 15,093,884
  - diff : 269,168 Winston **LESS** expected
 
- larger_file.png (53.908 KB)
  - estim : 44,149,059 
  - actual: 43,379,377
  - diff : 769,682 Winston **LESS** expected     
 
- ui_heart.png + ui_key.png (2 files, 724 bytes)
  - estim : 20,317,814 
  - actual: 18,772,287
  - diff : 1,545,527 Winston **LESS** expected
  
- bat_animation.png (262 bytes)
  - estim : 15,931,875 
  - actual: 15,162,193
  - diff : 769,682 Winston **LESS** expected

2021-07-14 20:31 UTC, arielmelendez commented on src/common.ts
> +	if (!Number.isInteger(winston)) throw new Error(`Winston value not an integer: ${winston}`);
It's just a limitation of the number system. For 0-9AR (0-~9.9 trillion Winston), we'll get about 4-5 digits of precision here. That's probably fine.

2021-07-14 20:34 UTC, arielmelendez commented on src/constants.ts
> +export const minimumArDriveCommunityTip = 0.000_010_000_000;
Nit: Knowing what unit it's in from the could be helpful. e.g. `minArDriveCommunityTipAR`

2021-07-14 20:36 UTC, arielmelendez commented on src/constants.ts
> +export const assumedMetadataTxPrice = 0.000_002_500_000;
Same idea here, e.g. `assumedMetadataTxARPrice`

2021-07-14 20:42 UTC, arielmelendez commented on src/node.test.ts
> +	this.timeout(10000);
We shouldn't write unit tests that hit the network. Only end-to-end tests should do that. We can redesign this function for testability if we provide for an object or function type that retrieves pricing data as a parameter to estimateArCost (with a sensible default parameter value for most normal use cases). If we do that, then we can stub the response from it and make sure the returned value is exactly what we expect.

2021-07-14 20:47 UTC, arielmelendez commented on src/node.ts
> +	return arCost + (await getArDriveCommunityTip(arCost));
`getArDriveCommunityTip` is the piece that needs to be factored out/parameterized so that you can unit test this function. You need an object/interface type like `ArCommunityTipReader` which you could then mock/stub in your unit test.

2021-07-14 20:54 UTC, arielmelendez commented on src/smartweave.ts
> +	if (!isTipPercentageFromSettings) getExactArDriveTipSetting();
Style nit: Move the code execution into braces and on its own line.

2021-07-14 20:59 UTC, arielmelendez commented on src/smartweave.ts
> +		isTipFromSettingsLoading = false;
Consider using a `finally` block to set `isTipFromSettingsLoading` to `false`.

2021-07-14 21:00 UTC, arielmelendez requested changes
A few minor things. But the major one is not to hit the network during unit tests.

2021-07-16 00:04 UTC, arielmelendez commented on src/common.test.ts
> +	it('correctly coverts with negative winston values', () => {
Nit: coverts -> converts

2021-07-16 00:17 UTC, arielmelendez commented on src/node.test.ts
> +			resolve(minArDriveCommunityARTip);
So if the minimum AR tip amount changes, the tests below will fail. That could be good or bad depending on what you're trying to achieve. Since the focus of the test ins't making sure that the minimum value is something specific, I'd recommend using a numeric literal here rather than importing the constant.

2021-07-16 00:21 UTC, arielmelendez commented on src/node.ts
> +				totalArweaveMetadataPrice += assumedMetadataTxARPrice;
It still surprises me that we can't precompute the total metadata size, divide by the number of files, get an AR quote on that, and then multiply by the number of files again to get a pretty close estimate.

2021-07-16 00:28 UTC, arielmelendez commented on src/public/ardrive_community_oracle.ts
> +const communityTipBlockHeight = 578358;
This is worth a comment explaining the value.

2021-07-16 00:30 UTC, arielmelendez commented on src/public/ardrive_community_oracle.ts
> +			if (arDriveTipPercentage !== undefined) {
Moved this outside the try.

2021-07-16 00:45 UTC, arielmelendez commented on src/public/ardrive_community_oracle.ts
> +		while (isFetchingTipSetting) {
I think we can remove this loop now since only 1 caller at a time will ever actually try to get the data.

2021-07-16 00:47 UTC, arielmelendez commented on src/public/ardrive_community_oracle.ts
> +		while (isFetchingTipSetting) {
This was only ever necessary if we expected callers to await on it, but your doc block says NOT to use it that way.

2021-07-16 00:51 UTC, arielmelendez commented on src/public/gateway_oracle.ts
> +		return getWinston(byteCount);
Consider moving the implementation of getWinston here and replacing calls to it in bundles.ts with calls to a GatewayOracle object.

2021-07-16 00:53 UTC, arielmelendez requested changes
Major issue: Why does using `votes` work?
Minor issues: A few in my other comments.

2021-07-16 01:52 UTC, fedellen commented
> Major issue: Why does using `votes` work?

Because using the block height version of the contract read we are searching through the `votes` array for the last vote. The setting for fee hasn't been created on that version of the contract. This is what the contract looks like during this block height contract read (minimized):

```
{
  name: 'ArDrive',
  ticker: 'ARDRIVE',
  balances: {
     // ...
   },
   vault: {
     // ...
   },
   votes: [
      // ...
      },
      // This is the last vote when using block height 578358
      {
        status: 'active',
        type: 'set',
        note: 'Setting ArDrive Data Upload fee',
        yays: 0,
        nays: 0,
        voted: [],
        start: 578358,
        totalWeight: 1603684484400,
        key: 'fee',
        value: 15
      }
   ],
   roles: {},
   settings: [
      [ 'quorum', 0.5 ],
      [ 'support', 0.15 ],
      [ 'voteLength', 2160 ],
      [ 'lockMinLength', 720 ],
      [ 'lockMaxLength', 788400 ],
      [ 'communityAppUrl', 'https://ardrive.io' ],
      [ 'communityDiscussionLinks', [Array] ],
      [
        'communityDescription',
        "We are a community focused on building the best private, secure, decentralized, pay-as-you-go, censorship-resistant and permanent data storage solution, for everyone.  With ArDrive's desktop, mobile and web apps, you can easily sync and share your public and private files from the PermaWeb."
      ],
      [ 'communityLogo', '1xQvwhgFF7573l5Ejb-5DHudo16R7aF0cTEKJMwsLAs' ]
   ]
}
```

2021-07-16 02:06 UTC, fedellen commented on src/node.ts
> +				totalArweaveMetadataPrice += assumedMetadataTxARPrice;
I've been focused on the estimation/testing side of this and haven't fully investigated the Metadata process. I can still dig further into this one and see if I can find a way, or at least find the reason why we can't

2021-07-16 15:53 UTC, arielmelendez commented on src/public/ardrive_community_oracle.ts
> +		if (isTipPercentageLatestFromSmartWeave || isFetchingTipSetting) {
Good catch

2021-07-16 15:55 UTC, arielmelendez commented on src/public/ardrive_community_oracle.ts
> +			const arDriveCommTipFromSettings: ['fee', number] = contract.settings.find(
This is the kind of change we would have realized we needed earlier if we factored out the contract reader and unit tested this code. We would have been forced to learn the schema of the returned data and tested against it.

2021-07-16 16:00 UTC, arielmelendez approved these changes
Good improvements. Thanks!

2021-07-19 12:11 UTC, jdaev submitted a review, later dismissed
Looks good to me

2021-07-21 22:26 UTC, arielmelendez commented on .mocharc.js
> +process.env.NODE_ENV = 'test';
Is this still required now that you removed the conditional code that relied upon this value?

2021-07-21 22:32 UTC, fedellen commented on .mocharc.js
> +process.env.NODE_ENV = 'test';
No, but it might be useful addition to the test setup

2021-07-21 22:52 UTC, arielmelendez commented on src/public/gateway_oracle.ts
> +		return response.json();
Let's make sure this is returning the correct type.

2021-07-21 22:52 UTC, arielmelendez commented on src/bundles.ts
> +						totalARPrice += common.winstonToAr(+winston); // Sum up all of the fees paid
Once we verify that getWinstonPriceForByteCount is returning the correct type, let's remove the `+` in `+winston`.

2021-07-21 23:07 UTC, arielmelendez commented on src/public/ardrive_community_oracle.test.ts
> +	it('returns a decimal to be used as a percentage using the `getArDriveTipPercentage` function', async () => {
Nit: I think the test would read ok with a description of:
'`getArDriveTipPercentage` function returns a decimal to be used as a percentage'

2021-07-21 23:09 UTC, arielmelendez commented on src/public/ardrive_community_oracle.test.ts
> +	it('returns a decimal to be used as a percentage using the `getArDriveTipPercentage` function', async () => {
The same applies to the tests below.

2021-07-21 23:12 UTC, arielmelendez commented on src/public/ardrive_community_oracle.ts
> +	async setExactTipSettingInBackground(
Any thoughts on whether this function should run if the cachedArDriveTipPercentage is set already?

2021-07-21 23:22 UTC, arielmelendez commented on src/public/ardrive_community_oracle.test.ts
> +	it('returns the `minArDriveCommunityARTip` if the calculated community tip is a smaller value', async () => {
There should be a complimentary test that if the tip is larger than the minimum that it returns that value. Also the function name should be in the test description. Would it help if you used a nested describe block for each batch of  test cases for each function?

2021-07-21 23:30 UTC, arielmelendez commented on src/public/ardrive_community_oracle.ts
> +			if (communityTipValue) {
If the community tip value were voted to be 0 (oh nooooo!), this would be falsey and end up returning the hardcoded default. I'd say that you should consider checking against undefined explicitly, but the Promise is typed to deliver a number. Under the hood, you're calling through to `readContract` and I'm not sure how it behaves under adverse conditions.

2021-07-21 23:37 UTC, arielmelendez commented on src/public/smartweave_oracle.ts
> +export class SmartWeaveContractOracle implements ContractOracle {
Nit: add a line of whitespace

2021-07-21 23:38 UTC, arielmelendez commented on src/public/smartweave_oracle.ts
> +		if (!arDriveCommTipFromSettings) {
Would this misbehave if the community tip were simply voted and set to 0?

2021-07-21 23:39 UTC, arielmelendez requested changes
Left a few minor comments. We're near the finish line here!

2021-07-22 02:40 UTC, fedellen commented on src/public/ardrive_community_oracle.ts
> +			if (communityTipValue) {
Thats true. This value is handled under the hood, it could in theory be a negative number as well.

Should we return the default, or error out if the value were a negative?

2021-07-22 03:42 UTC, fedellen commented on src/public/smartweave_oracle.ts
> +		if (!arDriveCommTipFromSettings) {
No, the type for `arDriveCommTipFromSettings` is `[string, unknown] | undefined`.

The value of `arDriveCommTipFromSettings[1]` in the tuple is unknown and not being checked here

2021-07-22 03:43 UTC, fedellen commented on src/public/smartweave_oracle.ts
> +		if (!arDriveCommTipFromSettings) {
I will add an explicit type declaration here to be more clear though

2021-07-22 03:44 UTC, arielmelendez commented on src/public/smartweave_oracle.ts
> +		if (!arDriveCommTipFromSettings) {
AH, good call. Thanks!

2021-07-22 03:44 UTC, fedellen commented on src/public/smartweave_oracle.ts
> +		if (!arDriveCommTipFromSettings) {
Although the function above has a similar issue where it would misbehave, I think I'll add in that the community tip cannot be a negative here

2021-07-22 14:12 UTC, arielmelendez commented on src/public/community_oracle.ts
> +	cachedArDriveTipPercentage: number | undefined;
Nit: Generally I think you'd want to use getters here that you could both use internally in implementations and stub if necessary for testing.

2021-07-22 14:13 UTC, arielmelendez submitted a review, later dismissed
Great updates!

2021-07-24 17:28 UTC, agsuy commented
Public folder was mean to include everything ArFS public related.
Public drives, sharing, etc.

smartweave.ts and gateway.ts both live at /src  
All our files related to nodes and arweave interaction are placed at /src as well.

arweave.ts should be moved to /src as well. (do not recall how it ended at /src/public tbh)

Given the above I would move every file on` /src/public` to` /src` bar:

- sharing.ts
- drives.ts
- arfs.ts

2021-07-24 17:34 UTC, agsuy requested changes
Please see my comments about where files should live above.
I would like to remain consistent with our current file/folder structure

2021-07-28 19:54 UTC, agsuy approved these changes
Lgtm!

2021-07-30 16:34 UTC, arielmelendez approved these changes

2021-08-02 20:46 UTC, merged