PE-477: Create manifests
ardriveapp/ardrive-core-js pull request #79
Opened 2021-11-15 21:38 UTC by fedellen

This PR adds the create manifest changes from https://github.com/ardriveapp/ardrive-cli/pull/137 to the new migrated core.

2021-11-22 19:44 UTC, arielmelendez commented on src/ardrive.ts
> +		folderId,
This API design makes it possible to pass an inconsistent folderId and driveId. Would it make more sense for us to just eat the getDriveIdForFolderId call every time to make sure we always get the right driveId?

2021-11-22 19:46 UTC, arielmelendez commented on src/ardrive.ts
> +		if (!driveId) {
Everything from here to `folderId ??= drive.rootFolderId;` creates the possibility for lots of different permutations of things to happen. This function's API is borderline hard to use correctly.

2021-11-22 19:50 UTC, arielmelendez commented on src/ardrive.ts
> +		if (!driveId) {
Consider making a private function that takes trusted driveId and folderId. Then have public functions that take one or the other but not both.

2021-11-22 20:00 UTC, arielmelendez commented on src/ardrive.ts
> +		const filesAndFolderNames = await this.arFsDao.getPublicNameConflictInfoInFolder(folderId);
There's a lot going on from here to the bottom of this function. Can we factor some of it out to testable helper functions and compose those together in a way that is readable and comprehensible? And then also test those?

2021-11-22 20:02 UTC, arielmelendez commented on src/ardrive.ts
> +		const uploadFileResult = await this.arFsDao.uploadPublicFile({
No dry run option?

2021-11-22 20:03 UTC, arielmelendez commented on src/ardrive.ts
> +		const { tipData, reward: communityTipTrxReward } = await this.sendCommunityTip({
Consider dry run option

2021-11-22 20:04 UTC, arielmelendez commented on src/ardrive.ts
> +			links: [`arweave.net/${uploadFileResult.dataTrxId}`, ...fileLinks]
How did we decide on the name and type of "links"? Just want to make sure I know what other use cases we have in mind for it and when to expect there to be multiple entries here.

2021-11-22 20:07 UTC, arielmelendez commented on src/arfs/arfs_file_wrapper.ts
> +export class ArFSManifestToUpload implements ArFSEntityToUpload {
Add tests

2021-11-22 20:09 UTC, arielmelendez commented on src/types/ardrive_types.ts
> +export interface Manifest {
Could use a docblock explaining the structure. It's confusing that there's an inner member named `manifest` whose type is actually a hardcoded string.

2021-11-22 20:09 UTC, arielmelendez requested changes
Left a few comments about API usability and need for tests.

2021-11-22 21:02 UTC, fedellen commented on src/ardrive.ts
> +		const uploadFileResult = await this.arFsDao.uploadPublicFile({
Dry run seems to be working just fine on `create-manifest`. It is never referred to in the ArDrive methods, only passed down through the constructors.

2021-11-22 21:08 UTC, fedellen commented on src/ardrive.ts
> +			links: [`arweave.net/${uploadFileResult.dataTrxId}`, ...fileLinks]
There will always be multiple entries here, unless used on a completely empty folder or drive (maybe that case should error out?).

As for the name and type of "links", I just added that in there for convenience during testing after taking over Phil's branch. It seems very useful to have links displayed in some form, as users can use the generated manifest links to permanently access their files.

2021-11-22 21:54 UTC, fedellen commented on src/ardrive.ts
> +		folderId,
I was originally handling this at the CLI layer, as they are forbidden in conjunction together. But since moving the method back to Core, we should absolutely handle the case where both are provided. 

Added here: 944f9b1

2021-11-22 22:21 UTC, fedellen commented on src/ardrive.ts
> +		const filesAndFolderNames = await this.arFsDao.getPublicNameConflictInfoInFolder(folderId);
I'm working on an integration test that wraps this whole method before I start this refactor. Currently stuck on stubbing out a `FolderHierarchy`, but I'll be digging more into it tonight/tomorrow.

2021-11-22 22:22 UTC, fedellen commented on src/types/ardrive_types.ts
> +export interface Manifest {
Added information from the manifest SPIKE to the some docblocks: 18629ac

2021-11-23 17:17 UTC, fedellen commented on src/ardrive.ts
> +		if (!driveId) {
Hmm, missed this last comment before. 

Maybe we shouldn't accept both driveID and folderID at the Core level and instead provide that convenience at the CLI layer by gathering the root folderID if a driveID is specified before calling the ArDrive method

2021-11-23 17:19 UTC, fedellen commented on src/ardrive.ts
> +		const filesAndFolderNames = await this.arFsDao.getPublicNameConflictInfoInFolder(folderId);
Hierarchy is now stubbed! Got an integration test wrapped around this function and added a few refactors that moves this logic elsewhere

2021-11-23 17:20 UTC, fedellen commented on src/arfs/arfs_file_wrapper.ts
> +export class ArFSManifestToUpload implements ArFSEntityToUpload {
Ah, this file could use some testing too. I'll see what I can do

2021-11-23 20:35 UTC, fedellen commented on src/ardrive.ts
> +		const { tipData, reward: communityTipTrxReward } = await this.sendCommunityTip({
Dry run is working, its tested using dry run in integration.

2021-11-23 20:36 UTC, fedellen commented on src/arfs/arfs_file_wrapper.test.ts
> +// describe('ArFSFolderToUpload class');
Implement these, quick coverage wins

2021-11-23 20:38 UTC, fedellen commented on src/arfs/arfsdao.ts
> +	async prepareManifest(
This function seems redundant now that the sorting implementation has moved to ArFSManifestToUpload. We should just call these from the ArDrive class

2021-11-23 20:39 UTC, fedellen commented on tests/integration/ardrive.int.test.ts
> +	// const stubFolderStructure: ArFSPublicFileOrFolderWithPaths[] =
Excise commented code

2021-11-23 20:40 UTC, fedellen commented on tests/integration/ardrive.int.test.ts
> +				folders: [{ folderName: 'CONFLICTING_FOLDER_NAME', folderId: stubEntityID }]
We don't test or handle manifest to folder conflict yet

2021-11-23 20:41 UTC, fedellen commented on tests/stubs.ts
> +	fileId?: FileID;
Implement these parameters on stubPrivateFile to avoid future confusion

2021-11-23 21:52 UTC, fedellen commented on src/ardrive.ts
> +		if (!driveId) {
I've applied this API change in the latest commits. We only accept a folderID at both layers

2021-11-23 21:53 UTC, fedellen commented on tests/integration/ardrive.int.test.ts
> +				folders: [{ folderName: 'CONFLICTING_FOLDER_NAME', folderId: stubEntityID }]
Handled and tested

2021-11-24 16:47 UTC, arielmelendez commented on src/ardrive.ts
> +			return { ...emptyArFSResult, links: [] };
Why isn't this an error if there's a folder name conflict?

2021-11-24 16:48 UTC, arielmelendez commented on src/ardrive.ts
> +		const filesAndFolderNames = await this.arFsDao.getPublicNameConflictInfoInFolder(folderId);
It's looking much better thanks!

2021-11-24 16:49 UTC, arielmelendez commented on src/ardrive.ts
> +			(path) => `arweave.net/${uploadFileResult.dataTrxId}/${path}`
No https://?

2021-11-24 16:49 UTC, arielmelendez commented on src/ardrive.ts
> +			links: [`arweave.net/${uploadFileResult.dataTrxId}`, ...fileLinks]
If we add https:// do so here as well.

2021-11-24 16:53 UTC, arielmelendez commented on src/arfs/arfs_file_wrapper.test.ts
> +				id: '0000000000000000000000000000000000000000000'
Should we use some alternative IDs here to make sure things are ending up in the right slots?

2021-11-24 17:01 UTC, arielmelendez commented on src/arfs/arfs_file_wrapper.test.ts
> +	it('constructs a manifest compatible with arweave gateways', () => {
How difficult would it be to generate the transaction that we would send and ensure that it's constructed properly? i.e. that the content type is set correctly in the tags.

2021-11-24 17:10 UTC, fedellen commented on src/arfs/arfs_file_wrapper.test.ts
> +		// Expect index path to be the first file
```suggestion
		// Expect index path to be linked to index.html
```

2021-11-24 17:16 UTC, arielmelendez commented on src/arfs/arfs_file_wrapper.ts
> +		// Use index.html in the specified folder if it exists, otherwise show first file found
Is this what arkb does for multifile uploads? Just curious

2021-11-24 17:17 UTC, arielmelendez commented on src/arfs/arfs_file_wrapper.ts
> +			throw new Error(`Files greater than "${+maxFileSize - 1}" bytes are not yet supported!`);
What's with the -1? Is maxFileSize not actually the max?

2021-11-24 17:17 UTC, arielmelendez commented on tests/integration/ardrive.int.test.ts
> +	const differentLastModifiedDate = new UnixTime(1337);
💪

2021-11-24 17:22 UTC, arielmelendez approved these changes
Approved with some open questions.

2021-11-24 17:31 UTC, fedellen commented on src/arfs/arfs_file_wrapper.ts
> +			throw new Error(`Files greater than "${+maxFileSize - 1}" bytes are not yet supported!`);
I found this error message to be imprecise (by 1 byte) when implementing unit tests around it. We're checking if the provided file size is greater than or equal to the max file size variable here.

2021-11-24 17:34 UTC, fedellen commented on src/arfs/arfs_file_wrapper.ts
> +		// Use index.html in the specified folder if it exists, otherwise show first file found
They have the same behavior. 

```ts
// arkb buildManifest
   if (Object.keys(paths).includes('index.html')) {
        index = 'index.html';
      } else {
        index = Object.keys(paths)[0];
      }
```

2021-11-24 17:38 UTC, fedellen commented on src/ardrive.ts
> +			(path) => `arweave.net/${uploadFileResult.dataTrxId}/${path}`
Added: 3aaacf2

2021-11-24 17:43 UTC, arielmelendez commented on src/arfs/arfs_file_wrapper.ts
> +			throw new Error(`Files greater than "${+maxFileSize - 1}" bytes are not yet supported!`);
Hmm, should it internally be ">" rather than ">="?

2021-11-24 17:45 UTC, fedellen commented on src/ardrive.ts
> +			return { ...emptyArFSResult, links: [] };
Added: ff9cbef

2021-11-24 17:53 UTC, fedellen commented on src/arfs/arfs_file_wrapper.test.ts
> +				id: '0000000000000000000000000000000000000000000'
749e784

2021-11-24 17:58 UTC, fedellen commented on src/arfs/arfs_file_wrapper.test.ts
> +	it('constructs a manifest compatible with arweave gateways', () => {
Its probably possibly to directly use the arweave library to do this here. I'd have to dig around our arfs methods some more to get started But, it seems seems like check would be at the integration test level so we know that our own methods will apply the content type correctly.

2021-11-24 18:07 UTC, fedellen commented on src/arfs/arfs_file_wrapper.ts
> +			throw new Error(`Files greater than "${+maxFileSize - 1}" bytes are not yet supported!`);
Actually, checking for greater than or equal to is the imprecise part here. Not the error message.

Updated: 749e784

2021-11-24 19:16 UTC, arielmelendez approved these changes

2021-11-30 20:49 UTC, merged