feat(cli migration): takes functionality from CLI into core PE-461
ardriveapp/ardrive-core-js pull request #83
Opened 2021-11-18 18:49 UTC by matibat

2021-11-18 20:15 UTC, matibat reviewed
TODO:
- Add the missing docblocks
- Implement the pending tests
- Remove all calls to `console.debug`

2021-11-18 20:15 UTC, matibat commented on src/ardrive.ts
> +const pipelinePromise = promisify(pipeline);
Make a tech_debt ticket: Remove all `promisify` occurrences after we bump the node version to 15^

2021-11-18 20:15 UTC, matibat commented on src/ardrive.ts
> +	 */
Update dockblock

2021-11-18 20:15 UTC, matibat commented on src/ardrive_anonymous.ts
> +	 */
Update docblock

2021-11-18 20:15 UTC, matibat commented on src/arfs/arfs_entities.ts
> +	getEntity<T = ArFSPublicFile | ArFSPublicFolder>(): T {
Add docblock here

2021-11-18 20:15 UTC, matibat commented on src/arfs/arfs_entities.ts
> +	getEntity<T = ArFSPublicFile | ArFSPublicFolder>(): T {
Add docblock here

2021-11-18 20:15 UTC, matibat commented on src/arfs/arfsdao_anonymous.ts
> +	async downloadFileData(fileTxId: TransactionID): Promise<Readable> {
Add docblock here

2021-11-18 20:15 UTC, matibat commented on src/utils/stream_decrypt.test.ts
> +});
IMPLEMENT THE TESTS!

2021-11-22 17:51 UTC, fedellen commented on src/arfs/arfs_entities.ts
> +	constructor(private readonly _entity: ArFSPublicFile | ArFSPublicFolder, hierarchy: FolderHierarchy) {
Is this significant here? It seems like this would just increase the surface area for testing

2021-11-22 17:53 UTC, fedellen commented on src/ardrive_anonymous.ts
> +		privateFile: ArFSPublicFile,
```suggestion
		publicFile: ArFSPublicFile,
```

2021-11-22 17:54 UTC, fedellen commented on src/ardrive_anonymous.ts
> +				console.debug(`Updating the utimes for ${path}: ${remoteFileLastModifiedDate}`);
Do these `console.debug`s show up in the output?

2021-11-22 20:13 UTC, matibat commented on src/ardrive_anonymous.ts
> +				console.debug(`Updating the utimes for ${path}: ${remoteFileLastModifiedDate}`);
Yes.
**To-Do** remove these

2021-11-22 20:28 UTC, matibat commented on src/arfs/arfs_entities.ts
> +	constructor(private readonly _entity: ArFSPublicFile | ArFSPublicFolder, hierarchy: FolderHierarchy) {
This commit clarifies the implementation: bd6fd2dc4dc99a7d6025be49483cd30057136411

I added a getter for the entity without paths

2021-11-22 20:29 UTC, matibat commented on src/arfs/arfsdao_anonymous.ts
> +	async downloadFileData(fileTxId: TransactionID): Promise<Readable> {
1f50199c9f34728486f1357bc6164057fe58d0aa

2021-11-22 20:29 UTC, matibat commented on src/ardrive.ts
> +	 */
1f50199c9f34728486f1357bc6164057fe58d0aa

2021-11-22 20:29 UTC, matibat commented on src/ardrive_anonymous.ts
> +	 */
1f50199c9f34728486f1357bc6164057fe58d0aa

2021-11-22 20:29 UTC, matibat commented on src/arfs/arfs_entities.ts
> +	getEntity<T = ArFSPublicFile | ArFSPublicFolder>(): T {
1f50199c9f34728486f1357bc6164057fe58d0aa

2021-11-22 20:29 UTC, matibat commented on src/arfs/arfs_entities.ts
> +	getEntity<T = ArFSPublicFile | ArFSPublicFolder>(): T {
1f50199c9f34728486f1357bc6164057fe58d0aa

2021-11-22 20:41 UTC, matibat commented on src/ardrive_anonymous.ts
> +		privateFile: ArFSPublicFile,
762265849ffaac30decef3d29d7eb3ca3195c4bf

2021-11-22 22:45 UTC, matibat commented on src/utils/stream_decrypt.test.ts
> +});
59beb369539a57f7f150308a68a0903c9a231360

2021-11-22 22:48 UTC, matibat commented on src/ardrive_anonymous.ts
> +				console.debug(`Updating the utimes for ${path}: ${remoteFileLastModifiedDate}`);
There: a6e4629d5d2bb1b1335d865295841ce71be79666

2021-11-22 22:53 UTC, matibat commented on src/arfs/arfs_entities.ts
> +	constructor(private readonly _entity: ArFSPublicFile | ArFSPublicFolder, hierarchy: FolderHierarchy) {
I think it doesn't imply testing more stuff here except for the `getEntity()` which returns exactly the `readonly entity` instance :thinking:

2021-11-22 23:08 UTC, matibat commented on src/utils/stream_decrypt.ts
> +		this.encryptedData = Buffer.concat([this.encryptedData, chunk]);
The standard accepts the chunk to be a `string` also; `encoding` has its own type
```suggestion
	_transform(chunk: Buffer | string, encoding: BufferEncoding, next: (err?: Error, data?: Buffer) => void): void {
		if (!(chunk instanceof Buffer)) {
			chunk = Buffer.from(chunk, encoding);
		}
		this.encryptedData = Buffer.concat([this.encryptedData, chunk]);
```

2021-11-23 01:04 UTC, fedellen commented on src/arfs/arfs_entities.ts
> +	constructor(private readonly _entity: ArFSPublicFile | ArFSPublicFolder, hierarchy: FolderHierarchy) {
I was mostly referring to just changing the variable to private readonly. But, it shouldn't actually make a difference in surface area because the compiler would tell us if something was incompatible. Resolving this

2021-11-23 16:59 UTC, arielmelendez commented on src/utils/query.ts
> +export function buildQuery({ tags = [], cursor, owner, sort = DESCENDING_ORDER, ids }: BuildGQLQueryParams): GQLQuery {
How large can this scale? What if there's, e.g. 10,000 files in a drive that's being downloaded?

2021-11-23 17:01 UTC, arielmelendez commented on src/utils/local_storage_conflict_resolution.ts
> +export async function proceedWritingFile(
consider `shouldProceedWritingFile/Folder` since `proceed` sounds like a command.

2021-11-23 17:06 UTC, arielmelendez commented on src/ardrive_anonymous.ts
> +			} else if (entity.entityType === 'file') {
Double check that manifests are just a file type

2021-11-23 17:12 UTC, arielmelendez commented on src/arfs/arfs_entities.ts
> +	constructor(private readonly _entity: ArFSPublicFile | ArFSPublicFolder, hierarchy: FolderHierarchy) {
If there's a getter, and if we don't have any functional mocking requirements, then I think we can just make it `readonly` rather than `private readonly`.

2021-11-23 18:47 UTC, arielmelendez commented on src/ardrive.ts
> +	 * @param maxDepth - the max depht in the file hierarchy
typo: `depht` --> `depth`

2021-11-23 18:50 UTC, arielmelendez commented on src/ardrive.ts
> +	 * @param path - a path in local storage
This should be more specific... is it a folder path? A file path? Either?

2021-11-23 18:54 UTC, arielmelendez commented on src/ardrive.ts
> +		maxDepth: number,
Consider a type, e.g. TreeDepth, that ensures the number is a non-negative integer OR positive infinity (if that value is valid).

2021-11-23 19:24 UTC, arielmelendez commented on src/ardrive.ts
> +		const rootFolder = folderEntityDump[0];
How reliable is this?

2021-11-23 19:26 UTC, arielmelendez commented on src/ardrive.ts
> +		const basePath = rootFolderPath.replace(/\/[^/]+$/, '');
What are you trying to accomplish here and why can't a built-in type or common utility accomplish it?

2021-11-23 19:29 UTC, arielmelendez commented on src/ardrive.ts
> +		const folderEntityDump = await this.listPrivateFolder({ folderId, maxDepth, includeRoot: true, driveKey });
Calling this `folderEntityDump` is misleading - it also contains files. Calling it a `Dump` seems redundant. Consider renaming to `filesAndFolders`.

2021-11-23 19:35 UTC, arielmelendez commented on src/ardrive.ts
> +		const allCipherIVs = await this.arFsDao.getCipherIVOfPrivateTransactionIDs(allFileDataTransactionIDs);
Why is this necessary? Aren't the cipherIVs already in all the file objects?

2021-11-23 19:37 UTC, arielmelendez commented on src/ardrive.ts
> +		const allCipherIVs = await this.arFsDao.getCipherIVOfPrivateTransactionIDs(allFileDataTransactionIDs);
`listPrivateFolder` returns `Promise<ArFSPrivateFileOrFolderWithPaths[]>`. Top of that class body is:
```
export class ArFSPrivateFileOrFolderWithPaths extends ArFSFileOrFolderEntity implements ArFSWithPath {
	readonly cipher: string;
	readonly cipherIV: CipherIV;
	readonly path: string;
	readonly txIdPath: string;
	readonly entityIdPath: string;
```
Seems like everything you need should be there already?

2021-11-23 19:51 UTC, arielmelendez commented on src/ardrive.ts
> +		path: string,
File or folder path?

2021-11-23 19:53 UTC, fedellen commented on src/ardrive.ts
> +		const allCipherIVs = await this.arFsDao.getCipherIVOfPrivateTransactionIDs(allFileDataTransactionIDs);
That is the cipherIV for the meta data transaction, not the data transaction. We need to specifically grab the tags off of the data tx in order to decrypt it

2021-11-23 19:54 UTC, arielmelendez commented on src/ardrive.ts
> +		const remoteFileLastModifiedDate = Math.ceil(+privateFile.lastModifiedDate / 1000);
Nit: improve locality of reference by moving closer to where it's used.

2021-11-23 20:02 UTC, arielmelendez commented on src/ardrive.ts
> +		cipherIV?: CipherIV,
ArFSPrivateFile already has a cipherIV. Why add it as a separate field???

2021-11-23 22:58 UTC, arielmelendez commented on src/ardrive_anonymous.ts
> +	async downloadPublicFolder(
Mostly the same comments for this function as the private version

2021-11-23 23:05 UTC, arielmelendez commented on src/ardrive_anonymous.ts
> +			const encryptedDataStream = await this.arFsDao.downloadFileData(fileTxId);
It's not encrypted.

2021-11-23 23:14 UTC, arielmelendez commented on src/arfs/arfsdao.ts
> +	async getPrivateTransactionCipherIV(txId: TransactionID): Promise<CipherIV> {
Not convinced yet that we need these

2021-11-23 23:15 UTC, arielmelendez requested changes
A number of architectural questions and concerns, some naming things, and a few others.

2021-11-29 18:42 UTC, matibat commented
Outdated

2021-11-29 18:42 UTC, closed without merging