PE-639: Ask prompt option on uploads
ardriveapp/ardrive-core-js pull request #87
Opened 2021-11-22 20:51 UTC by fedellen

This PR adds support the `--ask` option in ArDrive Core. The growing conflict resolution logic has been moved out of the ArDrive method logic and into its own file.

The Core layer defines all of the types for each prompt to implement, which the CLI (or any other app) will optionally implement.

2021-12-02 15:26 UTC, fedellen commented on src/types/upload_conflict_types.ts
> +	| typeof askOnConflicts;
Consider if and how this effects the new manifest method

2021-12-03 10:46 UTC, matibat reviewed
Left just a few comments there.
It's looking good and it has very descriptive comments! I'll approve once I dev-test it a little

2021-12-03 10:46 UTC, matibat commented on src/utils/upload_conflict_resolution.ts
> +	switch (userInput.resolution) {
Isn't there a default case here?

2021-12-03 10:46 UTC, matibat commented on src/utils/upload_conflict_resolution.ts
> +}: ResolveFileNameConflictsParams): Promise<void> => {
I don't see any references to `this` here. Is this method really needing to be an arrow function?
```suggestion
export async function resolveFileNameConflicts ({
	wrappedFile,
	conflictResolution,
	destinationFileName: destFileName,
	nameConflictInfo,
	prompts
}: ResolveFileNameConflictsParams): Promise<void> {
```

2021-12-03 14:31 UTC, fedellen commented on src/utils/upload_conflict_resolution.ts
> +}: ResolveFileNameConflictsParams): Promise<void> => {
SGTM: a5d0d6e

2021-12-07 12:54 UTC, matibat approved these changes
It's properly working now! Thanks for that quick fix

2021-12-08 06:47 UTC, arielmelendez commented on src/utils/upload_conflict_resolution.ts
> +			wrappedFile.conflictResolution = upsertOnConflicts;
Comment says skip but returns upsertOnConflicts. And I think the logic should be skipping since the lastModifiedDate is the same.

2021-12-08 06:59 UTC, arielmelendez commented on src/utils/upload_conflict_resolution.ts
> +			wrappedFile.conflictResolution = upsertOnConflicts;
FWIW your tests pass because your test case thinks this is the correct behavior:
```
it('resolves wrappedFile.conflictResolution to upsert when there is a file to file name conflict in the destination folder and the file has a MATCHING last modified date and the resolution is set to upsert', async () => {
```

2021-12-08 07:08 UTC, arielmelendez commented on src/utils/upload_conflict_resolution.ts
> +			wrappedFile.conflictResolution = upsertOnConflicts;
I think the confusion might be around what it means to upsert. It means to update (if necessary) or insert if it does not exist. So the choice to be made is whether, when we encounter the same last modified date, we consider the files "the same" and NOT in need of an update (i.e. skip). Otherwise we might perform a wasteful upload.

2021-12-08 07:15 UTC, arielmelendez commented on src/utils/upload_conflict_resolution.ts
> +			wrappedFolder.conflictResolution = skipOnConflicts;
It's interesting that this is a failure case for files unless we're skipping on conflicts, but always a skip for folders. Perhaps it should be an error unless --skip is provided? What's the rationale here? I just worry that a user would either:
• think a folder has uploaded when it hasn't
• not ever realize that a folder didn't upload

2021-12-08 07:56 UTC, arielmelendez requested changes
Some open q's re: intended behavior.

2021-12-08 11:45 UTC, jdaev submitted a review, later dismissed

2021-12-08 14:28 UTC, fedellen commented on src/utils/upload_conflict_resolution.ts
> +			wrappedFile.conflictResolution = upsertOnConflicts;
I separated the case of skipping from the case of skipping during upsert so I could return a different behavior here at the ArDrive level. During a skip, we return an emptyArFSResult. On a skip due to upsert, we return an error to the user explaining that the file is skipped because it matches the file on chain

2021-12-08 14:33 UTC, fedellen commented on src/utils/upload_conflict_resolution.ts
> +			wrappedFolder.conflictResolution = skipOnConflicts;
Throwing an error during a bulk method can result in transaction information being lost to the user. File transactions can be created and uploaded before the error throwing case. The JSON result with transaction IDs would never be sent to the user because of the thrown error

The solution I used here was to never throw errors on the bulk folder method. I was toying around with adding an `errors: []` field to the JSON output as an alternative solution, but it seemed intrusive to the output API.

Now, given the context of glob uploads and errors that could occur during that process, it might be a better idea to go with that `errors` field. What are your thoughts?

2021-12-08 21:40 UTC, arielmelendez commented on src/utils/upload_conflict_resolution.ts
> +			wrappedFolder.conflictResolution = skipOnConflicts;
I think it could be worthwhile as long as the exit status is NOT 0. Might be good to see what other common command line tools do in this case. Let's huddle up later to discuss and/or start a Slack thread.

2021-12-08 21:46 UTC, arielmelendez submitted a review, later dismissed

2021-12-14 20:43 UTC, arielmelendez approved these changes

2021-12-14 20:50 UTC, merged