PE-677: adds a callback for notifying the download progress
ardriveapp/ardrive-core-js pull request #88
Opened 2021-11-23 15:07 UTC by matibat

2021-11-24 20:13 UTC, matibat commented on src/ardrive.ts
> -			});
The PR at CLI: https://github.com/ardriveapp/ardrive-cli/pull/165

2021-11-24 20:13 UTC, matibat commented on src/ardrive_anonymous.ts
> +	async downloadPublicFolder(folderId: FolderID, maxDepth: number): Promise<ArFSFolderToDownload> {
Suggestion: rename to `getPublicFolderToDownload`

2021-11-24 20:13 UTC, matibat commented on src/ardrive_anonymous.ts
> -	async downloadPublicFile(
**For the reviewer**
This stuff is unrelated to `ardrive-core-js`: to deal with write streams should be the task of the client implementation

2021-11-24 20:13 UTC, matibat commented on src/arfs/arfs_file_wrapper.ts
> +export class ArFSFileToDownload {
add docblock here

2021-11-24 20:13 UTC, matibat commented on src/arfs/arfs_file_wrapper.ts
> +export class ArFSFolderToDownload {
add docblock here

2021-11-24 20:13 UTC, matibat commented on src/arfs/arfs_file_wrapper.ts
> +	async getDataStream(): Promise<Duplex> {
add docblock here

2021-11-24 20:13 UTC, matibat commented on src/arfs/arfs_file_wrapper.ts
> +	get length(): number {
add docblock here

2021-11-24 20:13 UTC, matibat commented on src/arfs/arfs_file_wrapper.ts
> +	async getDecryptingStream(): Promise<Duplex> {
add docblock here

2021-11-24 20:13 UTC, matibat commented on src/arfs/arfs_file_wrapper.ts
> +	public get folders(): ArFSAnyFileOrFolderWithPaths[] {
add docblock here

2021-11-24 20:13 UTC, matibat commented on src/arfs/arfs_file_wrapper.ts
> +	public get files(): ArFSFileToDownload[] {
add docblock here

2021-11-24 20:13 UTC, matibat commented on src/arfs/arfs_file_wrapper.ts
> +	async hidratate(
add docblock here

2021-11-24 20:13 UTC, matibat commented on src/arfs/arfs_file_wrapper.ts
> +	getRelativePath(entity: ArFSAnyFileOrFolderWithPaths): string {
add docblock here

2021-11-24 20:13 UTC, matibat commented on src/arfs/arfsdao_anonymous.ts
> +	async downloadFileData(fileTxId: TransactionID): Promise<{ data: Duplex; length: number }> {
add docblock here

2021-11-24 21:20 UTC, matibat reviewed
Taking the still-valid comments of @arielmelendez from #83

2021-11-24 21:20 UTC, matibat commented on src/utils/query.ts
> +export function buildQuery({ tags = [], cursor, owner, sort = DESCENDING_ORDER, ids }: BuildGQLQueryParams): GQLQuery {
@arielmelendez
> How large can this scale? What if there's, e.g. 10,000 files in a drive that's being downloaded?
> We may have to do some client-side batching here in a addition to the paging enforced by the gql endpoint

2021-11-24 21:20 UTC, matibat commented on src/utils/local_storage_conflict_resolution.ts
> +export async function proceedWritingFile(
@arielmelendez 
> consider `shouldProceedWritingFile/Folder` since `proceed` sounds like a command.

2021-11-24 21:20 UTC, matibat commented on src/arfs/arfs_file_wrapper.ts
> +			} else if (entityWithPaths.entityType === 'file') {
@arielmelendez 
> Double check that manifests are just a file type

2021-11-24 21:20 UTC, matibat commented on src/ardrive.ts
> +	 * @param maxDepth - the max depht in the file hierarchy
@arielmelendez 
> typo: `depht` --> `depth`

2021-11-24 21:20 UTC, matibat commented on src/ardrive_anonymous.ts
> +	 * @param maxDepth - the max depht in the file hierarchy
@arielmelendez 
> typo: `depht` --> `depth`

2021-11-24 21:20 UTC, matibat commented on src/ardrive_anonymous.ts
> +	 * @param path - a path in local storage
@arielmelendez 
> This should be more specific... is it a folder path? A file path? Either?

2021-11-24 21:20 UTC, matibat commented on src/ardrive_anonymous.ts
> +		const rootFolder = folderEntityDump[0];
@arielmelendez 
> How reliable is this?

2021-11-24 21:20 UTC, matibat commented on src/arfs/arfs_file_wrapper.ts
> +		return this.rootFolderWithPaths.path.replace(/\/[^/]+$/, '');
@arielmelendez 
> What are you trying to accomplish here and why can't a built-in type or common utility accomplish it?

2021-11-24 21:20 UTC, matibat commented on src/ardrive.ts
> +		const folderEntityDump = await this.listPrivateFolder({ folderId, maxDepth, includeRoot: true, driveKey });
@arielmelendez 
> Calling this `folderEntityDump` is misleading - it also contains files. Calling it a `Dump` seems redundant. Consider renaming to `filesAndFolders`.

2021-11-24 21:20 UTC, matibat commented on src/ardrive_anonymous.ts
> +		const folderEntityDump = await this.listPublicFolder({ folderId, maxDepth, includeRoot: true });
@arielmelendez 
> Calling this `folderEntityDump` is misleading - it also contains files. Calling it a `Dump` seems redundant. Consider renaming to `filesAndFolders`.

2021-11-24 21:20 UTC, matibat commented on src/ardrive.ts
> +		const rootFolder = folderEntityDump[0];
@arielmelendez
> How reliable is this?

2021-11-24 21:20 UTC, matibat commented on src/utils/local_storage_conflict_resolution.ts
> +	const remoteFileLastModifiedDate = Math.ceil(+remoteFile.lastModifiedDate / 1000);
@arielmelendez 
> Nit: improve locality of reference by moving closer to where it's used.

2021-11-24 21:20 UTC, matibat commented on src/ardrive.ts
> +		maxDepth: number,
@arielmelendez 
> Consider a type, e.g. `TreeDepth`, that ensures the number is a non-negative integer OR positive infinity (if that value is valid).

2021-11-24 21:41 UTC, arielmelendez commented on src/arfs/arfs_file_wrapper.ts
> +	async hidratate(
Should not be async. Just add the dump into the constructor.

2021-11-24 21:43 UTC, arielmelendez commented on src/ardrive.ts
> +		const rootFolder = folderEntityDump[0];
Add and/or augment a test that ensures the root ends up at the 0 index.

2021-11-24 22:40 UTC, arielmelendez commented
Notes from our huddle:
1) We need to eliminate the circular dependencies, i.e. ardrive -> arfsdao -> arfsfiletodownload -> ardrive
2) We should simplify the ardrive API to something like:
```
async downloadPublicFolder(
			folderId: FolderID,
			maxDepth: TreeDepth,
			destFolder: string,
			progressCB?: (pctTotal: number, pctFile: number, curFileName: string, curFilePath: string) => void
		): Promise<void> {}
```
3) Split ArFSFileToDownload by privacy type to deal with unknown size of encrypted vs. known size of unencrypted at the constructor/interface level
4) Stream acquisition should be a DAO concern, not an ArDrive concern
5) Consider a fresh branch and try making a download file cupcake (initially without a progress bar maybe?)

2021-11-24 22:41 UTC, arielmelendez requested changes
See comment

2021-12-08 14:28 UTC, matibat commented
Outdated. Closing...

2021-12-08 14:28 UTC, closed without merging