PE-464: download file
ardriveapp/ardrive-core-js pull request #91
Opened 2021-11-29 15:11 UTC by matibat

2021-11-29 16:22 UTC, matibat reviewed
Cleanup needed

2021-11-29 16:22 UTC, matibat commented on src/arfs/arfs_entities.ts
> +export type ArFSAnyFileOrFolderWithPaths = ArFSPublicFileOrFolderWithPaths | ArFSPrivateFileOrFolderWithPaths;
Remove unused code

2021-11-29 18:36 UTC, matibat commented on src/arfs/arfsdao_anonymous.ts
> +	 * @returns {Promise<void>}
```suggestion
	 * @returns {Promise<{ data: Readable; length: number }>}
```

2021-11-30 18:12 UTC, fedellen commented on src/arfs/arfsdao_anonymous.ts
> +		const dataTxUrl = `${gatewayURL}${fileTxId}`;
This could be simplified a bit by just passing a fileId down. Doesn't look like we use any of the other fields within this scope

2021-11-30 18:15 UTC, fedellen commented on src/utils/query.ts
> +				${ids?.length ? `ids: [${ids.map((id) => `"${id}"`)}]` : ''}
I'm interested to see if there are any limitations in how many txIds we can pass in here. Its not relevant within the context of download-file though.

2021-11-30 18:19 UTC, fedellen commented on src/utils/stream_decrypt.ts
> +	private encryptedData: Buffer = Buffer.from(''); // TODO: is it possible to pop the stream data in a buffer-like manner?
I'm not entirely sure what these comments mean. So for private downloads, we need to convert it to a Buffer to decrypt, but with public downloads the data can always remain as a stream?

2021-11-30 18:21 UTC, fedellen commented on src/arfs/arfs_file_wrapper.ts
> +		writePromise.finally(this.setLastModifiedDate);
This seems to be the issue I ran into on the CLI side. We need to await this promise here or return it as the private file `write()` does

2021-11-30 18:26 UTC, fedellen commented on src/arfs/arfs_file_wrapper.ts
> +		}
This error case doesn't seem necessary if we just make the abstract fileEntity typesafe with ArFSPublicFile | ArFSPrivateFile

2021-11-30 18:30 UTC, fedellen requested changes
Looking good! This cupcake version is much easier to digest. Left comments on mostly minor things and a couple questions. 

Requesting changes because I am getting an error on the CLI side when dev-testing though, might be related to the public file `write()` implementation but I'm not positive

2021-11-30 21:24 UTC, arielmelendez commented on src/arfs/arfsdao_anonymous.ts
> +	 * @returns {Promise<void>}
Better yet, could we create an interface for this? e.g. `ReadableData`?

2021-11-30 21:25 UTC, matibat commented on src/arfs/arfs_file_wrapper.ts
> +		writePromise.finally(this.setLastModifiedDate);
It was a scope issue: References to `this` at setLastModifiedDate were all relative to the promise instead of the `ArFSFileToDownload`. See: 5818313

2021-11-30 21:28 UTC, arielmelendez commented on src/arfs/arfsdao_anonymous.ts
> +	 * Downloads the data of a public file into certain existing folder in the local storage
Comment needs updating.

2021-11-30 22:50 UTC, arielmelendez commented on src/utils/stream_decrypt.ts
> +	private encryptedData: Buffer = Buffer.from(''); // TODO: is it possible to pop the stream data in a buffer-like manner?
@matibat @vilenarios and I did some experiments to see if we could get downloading an encrypted file working with a streaming decipher rather than having to queue up all the encrypted bytes. The challenge is that the last 16 bytes of the whole file contain the authTag which is needed to set up the decipher.

We figured out a potential workaround: Using HTTP Range Requests to get the last 16 bytes of the file before trying to do the download, which itself would only request 0-(N-16) bytes. See https://developer.mozilla.org/en-US/docs/Web/HTTP/Range_requests for more.

To make use of this, we'll need:
1) A new Dao function to get an auth tag for a dataTx. It will need to compute the full file size of the encrypted data item using the metadata's reported unencrypted size and then put that through the `encryptedDataSize` function. That will give us the upper bound for the range request.
2) Do away with the StreamDecrypt class in favor of simply plugging together the pipes like so:
```
	async downloadPrivateFile(
		fileId: FileID,
		destFolderPath: string,
		driveKey: DriveKey
		// progressCB?: (pctTotal: number, pctFile: number, curFileName: string, curFilePath: string) => void
	): Promise<void> {
		const privateFile = await this.getPrivateFile({ fileId, driveKey });
		const fullPath = joinPath(destFolderPath, privateFile.name);
		const { data } = await this.arFsDao.getDataStream(privateFile);
		const fileKey = await deriveFileKey(`${fileId}`, driveKey);
		const fileCipherIV = await this.arFsDao.getPrivateTransactionCipherIV(privateFile.dataTxId);
		const iv: Buffer = Buffer.from(fileCipherIV, 'base64');
		const decipher = createDecipheriv('aes-256-gcm', fileKey, iv, { authTagLength: 16 });
		const authTag = await this.arFsDao.getAuthTagForDataTxId(privateFile.dataTxId);
		decipher.setAuthTag(authTag);
		const fileToDownload = new ArFSPrivateFileToDownload(privateFile, data, fullPath, decipher);
		await fileToDownload.write();
	}
```

2021-12-01 17:25 UTC, matibat commented on src/ardrive.ts
> +		const decipher = new StreamDecrypt(fileCipherIV, fileKey, authTag);
I didn't remove this wrapper class because of some errors regarding lengths and the `authTag`. I'm not sure if it is possible to directly pipe the `DecipherGCM` stream, or even if it's worth it.

It's currently working fine with a simpler implementation.

2021-12-01 17:25 UTC, matibat commented on src/ardrive.ts
> +		const decipher = new StreamDecrypt(fileCipherIV, fileKey, authTag);
TODO: remove these comments

2021-12-01 17:27 UTC, matibat commented on src/arfs/arfs_builders/arfs_file_builders.ts
>  	dataContentType: ContentType;
@fedellen this interface is a type for the parsed JSON data of the Metadata tx. It doesn't actually use our safe types, right?

2021-12-01 17:28 UTC, matibat commented on src/arfs/arfsdao.ts
> +		const length = new ByteCount(+headers['content-length']); // TODO: remove - it useless if we can compute the size before making the request
Remove unused field. Remove unused `ReadableData` type after that

2021-12-01 17:29 UTC, matibat commented on src/arfs/arfsdao.ts
> +				const authTag = Buffer.from('0123456789abcdef');
Is this the right way of allocating the buffer in memory? Surely there's a better approach ti instantiate this buff of length 16

2021-12-01 17:30 UTC, matibat commented on src/arfs/arfsdao_anonymous.ts
> +	 * @returns {Promise<void>}
**EDIT** no need to return the length of the streamed data
```suggestion
	 * @returns {Promise<Readable>}
```

2021-12-01 17:31 UTC, matibat commented on src/utils/stream_decrypt.ts
> +	}
**for the reviewer**
The decipher is instantiated here

2021-12-01 17:32 UTC, matibat commented on src/utils/stream_decrypt.ts
> +	}
**for the reviewer**
The data gets fed to this function and the decrypted data is pushed to the `StreamDecrypt`

2021-12-01 17:34 UTC, matibat commented on src/utils/stream_decrypt.ts
> +	}
**for the reviewer**
Finally, when there's no more data to consume the returned buffer of `this.decipher.final()` gets pushed into the `StreamDecrypt`

2021-12-02 07:12 UTC, arielmelendez commented on src/arfs/arfs_builders/arfs_file_builders.ts
>  	dataContentType: ContentType;
Good catch. It's interesting that the safe types weren't causing errors after JSON.parse? I think the better solution might be to make it a class type and be able to instantiate it from a JSON string, i.e. `FileMetaDataTransactionData.from(json);`

2021-12-02 17:04 UTC, arielmelendez commented on src/arfs/arfs_builders/arfs_file_builders.ts
>  	dataContentType: ContentType;
Let's create a tech debt ticket for this.

2021-12-02 17:13 UTC, arielmelendez commented on src/arfs/arfsdao.ts
> +		const fileCipherIvResult = results[0];
Should check result count.

2021-12-02 17:30 UTC, arielmelendez submitted a review, later dismissed

2021-12-03 09:37 UTC, matibat commented on src/arfs/arfs_file_wrapper.ts
> +		}
Fix applied by @arielmelendez at 30737770194e7e8fa0077d1f4132bf2aea098413

2021-12-03 09:37 UTC, matibat commented on src/arfs/arfsdao_anonymous.ts
> +		const dataTxUrl = `${gatewayURL}${fileTxId}`;
This change was applied

2021-12-03 09:45 UTC, matibat commented on src/arfs/arfsdao_anonymous.ts
> +	 * Downloads the data of a public file into certain existing folder in the local storage
af70483c0a03d5abcb89d6e63fca0d63e09b0bf0

2021-12-03 09:46 UTC, matibat commented on src/arfs/arfsdao_anonymous.ts
> +	 * @returns {Promise<void>}
af70483c0a03d5abcb89d6e63fca0d63e09b0bf0

2021-12-03 09:50 UTC, matibat commented on src/arfs/arfsdao.ts
> +		const fileCipherIvResult = results[0];
43598f5f4c59b1ba469f44229babc98aa28e234a

2021-12-03 13:45 UTC, matibat commented on src/utils/query.ts
> +				${ids?.length ? `ids: [${ids.map((id) => `"${id}"`)}]` : ''}
Hloover suggested keeping it below 100. It might not be the current limit, but he said `I’d keep it 100 for “future-proof”`

2021-12-03 13:47 UTC, matibat commented on src/utils/query.ts
> +				${ids?.length ? `ids: [${ids.map((id) => `"${id}"`)}]` : ''}
We might cover this case by having a wrapper on top of the `buildQuery` to deal with pagination and the limit of 100 queried entities

2021-12-03 14:45 UTC, matibat commented on src/arfs/arfs_builders/arfs_file_builders.ts
>  	dataContentType: ContentType;
https://ardrive.atlassian.net/browse/PE-749

2021-12-03 14:54 UTC, matibat commented on src/utils/query.ts
> +				${ids?.length ? `ids: [${ids.map((id) => `"${id}"`)}]` : ''}
Here the tech debt ticket: https://ardrive.atlassian.net/browse/PE-750

2021-12-03 16:26 UTC, fedellen approved these changes
Looking good!

2021-12-06 12:28 UTC, jdaev commented on src/utils/resolve_path.test.ts
> +describe('resolveLocalFilePath function', () => {
Why the empty tests?

2021-12-06 12:29 UTC, jdaev reviewed
Looks solid. Well done.
Left one question.

2021-12-06 13:12 UTC, matibat commented on src/utils/resolve_path.test.ts
> +describe('resolveLocalFilePath function', () => {
I only need confirmation in the test descriptions to proceed

2021-12-06 14:58 UTC, fedellen commented on src/utils/resolve_path.test.ts
> +	it('returns the provided path if the file exists');
So now we can provide:

test case 1:  `--dest-folder-name /path/to/existing_file.txt`
test case 2: `--dest-folder-name /path/to/folder` 
test case 3: ` --dest-folder-name /path/to/non_existent_file.txt`

I re-worded the descriptions as I read through the new function so I could break it down and understand them, but yours seem fine as is.

`returns the provided path if a file exists at the destination`
`returns the provided path concatenated with the default file name if a folder exists at the destination`
`returns the parent folder path concatenated with the default file name if the provided path does not exist but the parent directory does`
`throws an error if provided path is invalid`

2021-12-06 15:13 UTC, fedellen commented on src/utils/resolve_path.ts
> +		// the path neither its parent exist
```suggestion
		// the path nor its parent folder exist
```

2021-12-06 21:26 UTC, arielmelendez commented on src/utils/resolve_path.ts
> +		// the path neither its parent exist
Technically speaking a `nor` requires a `neither`. So it should be:
```suggestion
		// neither path nor its parent exist
```

2021-12-06 21:49 UTC, arielmelendez commented on src/utils/stream_decrypt.test.ts
> +	it('fails while descrypting with wrong secrets', () => {
```suggestion
	it('fails while decrypting with wrong secrets', () => {
```

2021-12-06 21:55 UTC, arielmelendez commented on src/arfs/arfsdao.ts
>  	 * @returns {Promise<void>}
```suggestion
	 * @returns {Promise<Readable>}
```

2021-12-06 22:00 UTC, arielmelendez approved these changes

2021-12-06 23:36 UTC, arielmelendez commented on src/utils/resolve_path.ts
> +export function resolveLocalFilePath(destFolderPath: string, defaultFileName: string, stat = statSync): string {
I still find this function difficult to use correctly:
1) It's called `resolveLocalFilePath` without any explanation about what "resolving" means. An accompanying docblock could possibly help with that.
2) It takes a destFolderPath, but it's a valid use case for that to be a file. That's VERY confusing, especially in the absence of documentation.
3) You HAVE to provide a default file name. So if you know the filename you want to use, then you need to provide it again even though it's not useful.
4) The type for stat is not easily inferred. Could incorrect implementations of stat be provided accidentally?


It's also not clear to me that this logic should live in core. I think it would be simpler if core's download API just took a file path fore where the downloaded file should go. It could then leave decisions about where a file should go, given some arbitrary path, up to the client layer, i.e. the CLI. Think of it this way - why is this logic useful for users of Core? Who needs this functionality generally speaking? What does it have to do with ArFS or ArDrive?

2021-12-06 23:47 UTC, arielmelendez commented on src/utils/resolve_path.ts
> +export function resolveLocalFilePath(destFolderPath: string, defaultFileName: string, stat = statSync): string {
Also why does `downloadPrivateFile` use this, but downloadPublicFile does not?

2021-12-06 23:50 UTC, arielmelendez commented on src/utils/resolve_path.ts
> +export function resolveLocalFilePath(destFolderPath: string, defaultFileName: string, stat = statSync): string {
Wouldn't all of this be simpler from the core client's perspective if the public/private download APIs were like:
```
	async downloadPrivateFile(
		fileId: FileID,
		driveKey: DriveKey
		destFolderPath: string,
		destFileName?: string
		// progressCB?: (pctTotal: number, pctFile: number, curFileName: string, curFilePath: string) => void
	): Promise<void> {
```
where an undefined `destFileName` means to use the filename on ArDrive?

2021-12-06 23:51 UTC, arielmelendez commented on src/utils/resolve_path.ts
> +export function resolveLocalFilePath(destFolderPath: string, defaultFileName: string, stat = statSync): string {
Then all you'd need to do is `assertLocalPathExists` for `destFolderPath`

2021-12-06 23:52 UTC, arielmelendez requested changes
I have some concerns with the ease of use of the download APIs as it pertains to paths. I think we have too much logic in core that should instead be in the CLI layer.

2021-12-07 12:27 UTC, matibat commented on src/utils/resolve_path.ts
> +export function resolveLocalFilePath(destFolderPath: string, defaultFileName: string, stat = statSync): string {
I removed the responsibility of core to resolve the file path, that's now the task of CLI. Please review the variable/function/script names, I feel they a little confusing still.

2021-12-07 12:28 UTC, matibat commented on src/utils/resolve_path.test.ts
> +	it('returns the provided path if the file exists');
Those will surely be moved to the client layer

2021-12-07 13:34 UTC, matibat commented on src/ardrive.ts
> +		const outputFileName = defaultFileName ?? privateFile.name;
TODO: Ensure the double question mark checks for `undefined` values apart of `null`

2021-12-07 13:34 UTC, matibat commented on src/arfs/arfsdao.ts
> +	getAuthTagForPrivateFile = async (privateFile: ArFSPrivateFile): Promise<Buffer> =>
No `await` being used in this method, the `async` keyword is useless here

2021-12-07 13:34 UTC, matibat commented on src/arfs/arfsdao.ts
> +	getAuthTagForPrivateFile = async (privateFile: ArFSPrivateFile): Promise<Buffer> =>
There's no need for the method to be an arrow function, `this` isn't used here

2021-12-07 13:34 UTC, matibat commented on src/arfs/arfsdao.ts
> +		new Promise((resolve, reject) => {
The promise executor doesn't need to be an arrow function as there's no references to `this` inside

2021-12-07 13:34 UTC, matibat commented on src/arfs/arfsdao.ts
> +					resolve(authTag);
Should I reject if the `index !== 16` or trust the GW will return the right length?

2021-12-07 13:34 UTC, matibat commented on src/arfs/arfsdao.ts
> +				let index = 0;
Instead of `index`, use `responseByteCount`

2021-12-07 13:34 UTC, matibat commented on src/arfs/arfsdao.ts
> +				const authTag = Buffer.alloc(16);
Move the `16` to a constant `AUTH_TAG_LENGTH`

2021-12-07 13:34 UTC, matibat commented on src/utils/resolve_path.ts
> +import { statSync } from 'fs';
Remove unused source file

2021-12-07 13:34 UTC, matibat commented on src/utils/resolve_path.test.ts
> +describe('resolveLocalFilePath function', () => {
remove unused test file

2021-12-07 13:34 UTC, matibat commented on src/arfs/arfsdao.ts
> +				const authTag = Buffer.alloc(16);
Note the const is already defined at `stream_decrypt.ts`; consolidate it

2021-12-07 13:34 UTC, matibat commented on src/utils/common.ts
> +	return new ByteCount((+dataSize / 16 + 1) * 16);
We could use `bignum` for the `ByteCount` later on

2021-12-07 16:26 UTC, fedellen commented on src/ardrive.ts
> +	): Promise<void> {
This method and downloadUploadFile should be using object parameters. 4 parameters is pretty deep for positional parameters, especially ones that share types like destFolderPath and defaultFileName. 

And all outward facing ArDrive methods were refactored to use this pattern for API stability and extensibility

2021-12-07 16:42 UTC, arielmelendez commented on src/utils/common.ts
> +	return new ByteCount((+dataSize / 16 + 1) * 16);
I don't think we'll be working at bignum scale of bytes any time soon 😬

2021-12-07 19:39 UTC, arielmelendez commented on src/ardrive.ts
> +		const outputFileName = defaultFileName ?? privateFile.name;
From : https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Nullish_coalescing_operator
```
The nullish coalescing operator (??) is a logical operator that returns its right-hand side operand when its left-hand side operand is null or undefined, and otherwise returns its left-hand side operand.
```

2021-12-07 19:43 UTC, arielmelendez commented on src/ardrive_anonymous.ts
> +		destFolderPath: string,
As @fedellen mentioned elsewhere (perhaps another PR), since we have 2 positional parameters here that the same type and could potentially be reversed accidentally by a caller, we should an object argument with named parameters. The same goes for `downloadPrivateFile`.

2021-12-07 19:44 UTC, arielmelendez commented on src/arfs/arfsdao.ts
> +					resolve(authTag);
I'd reject if it's the wrong size

2021-12-08 02:16 UTC, arielmelendez requested changes
There's a few comments here and an ongoing team discussion about the behaviors of the CLI app given different permutations of folder and file existence.

2021-12-08 17:40 UTC, matibat commented on src/arfs/arfsdao.ts
> +				const authTag = Buffer.alloc(16);
7a273d7e11b85661ce7e59710bd9961931ee48a4

2021-12-08 17:41 UTC, matibat commented on src/arfs/arfsdao.ts
> +	getAuthTagForPrivateFile = async (privateFile: ArFSPrivateFile): Promise<Buffer> =>
fd4fa2a8944efb12febaacff65beacefc6ca21dd

2021-12-08 17:41 UTC, matibat commented on src/arfs/arfsdao.ts
> +		new Promise((resolve, reject) => {
fd4fa2a8944efb12febaacff65beacefc6ca21dd

2021-12-08 17:41 UTC, matibat commented on src/arfs/arfsdao.ts
> +					resolve(authTag);
40ceac412c6f19a76b9a92e79342483fb2d68929

2021-12-08 17:41 UTC, matibat commented on src/arfs/arfsdao.ts
> +				let index = 0;
40ceac412c6f19a76b9a92e79342483fb2d68929

2021-12-08 17:42 UTC, matibat commented on src/utils/resolve_path.ts
> +import { statSync } from 'fs';
8a56976d205992b317c6388a6b22b5bac4d0e956

2021-12-08 17:43 UTC, matibat commented on src/utils/resolve_path.test.ts
> +describe('resolveLocalFilePath function', () => {
8a56976d205992b317c6388a6b22b5bac4d0e956

2021-12-08 18:04 UTC, matibat commented on src/ardrive.ts
> +	): Promise<void> {
cbbc3031fc39a49e655e31c1aec31ed24f96bd88

2021-12-08 18:04 UTC, matibat commented on src/ardrive_anonymous.ts
> +		destFolderPath: string,
cbbc3031fc39a49e655e31c1aec31ed24f96bd88

2021-12-08 18:06 UTC, matibat commented on src/utils/resolve_path.test.ts
> +	it('returns the provided path if the file exists');
These were removed

2021-12-08 18:13 UTC, fedellen submitted a review, later dismissed

2021-12-08 18:31 UTC, arielmelendez commented on src/ardrive.ts
> +	}: DownloadPrivateFileArguments): Promise<void> {
Naming nit, but I think we need standards around this: Input names in the interface definition are "Parameters". Arguments are the variables/values that you pass in from the outside. The in-function references are parameters. Everywhere else in the codebase we refer to them as Parameters or Params so let's stick with the convention.

2021-12-08 18:42 UTC, arielmelendez commented on src/arfs/arfsdao.ts
> +		return new Promise(function (resolve, reject) {
Is there a reason we're creating a promise and using resolve/reject vs. simply returning or throwing? I don't see an async context here where we're trying to catch an exception.

2021-12-08 20:48 UTC, arielmelendez commented on src/ardrive.ts
> +	}: DownloadPrivateFileArguments): Promise<void> {
2b7d7e4

2021-12-08 20:49 UTC, arielmelendez submitted a review, later dismissed

2021-12-09 01:17 UTC, matibat commented on src/arfs/arfsdao.ts
> +		return new Promise(function (resolve, reject) {
Simplified the function by asking Axios to return a buffer: f217cf8a482423a70d1655f2507029f4843d2cfc

2021-12-09 01:24 UTC, arielmelendez submitted a review, later dismissed

2021-12-09 17:38 UTC, fedellen submitted a review, later dismissed

2021-12-09 19:47 UTC, fedellen approved these changes

2021-12-16 20:11 UTC, arielmelendez approved these changes

2021-12-17 20:55 UTC, fedellen approved these changes

2021-12-17 20:59 UTC, arielmelendez approved these changes

2021-12-20 19:20 UTC, merged