fix(create manifest): URL encode links for user output PE-743
ardriveapp/ardrive-core-js pull request #93
Opened 2021-11-30 21:50 UTC by fedellen

2021-11-30 23:17 UTC, arielmelendez submitted a review, later dismissed

2021-12-01 19:31 UTC, arielmelendez requested changes
Need an error case in core for an empty folder and a matching integration test.

2021-12-01 20:42 UTC, arielmelendez approved these changes

2021-12-01 20:46 UTC, jdaev approved these changes

2021-12-01 22:01 UTC, merged